cockroachdb/replicator

main_test.go
sink.go

This change fixes a bug when generating delete statements for tables with
composite key. The generated values did not have a comma separator.
Fixes #36
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/42)

cdc-sink: Fix SQL syntax error in composite key deletes

---

sink.go
sink_table.go
sink_table_test.go

This change uses a DELETE RETURNING in conjunction with the enclosing
transaction to eliminate the need to run the DELETE at the end of the UPSERT
process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/50)

cdc-sink: Eliminate a sql round-trip by DELETE RETURNING

---

url.go
url_test.go

This change limits the parser to only hexadecimal characters in the uniquer
part, and allows all hex characters in the schema_id part.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/49)

cdc-sink: Correct regex parsing

---

sink_table.go
sink_table_test.go

There was not a test for the case in which a CDC update is delivered twice.  As
it turns out, the COPY FROM acts as like INSERT, but with no way to ignore
conflicts. This change reverts the insert-message code to the previous
UPSERT-based approach.
An alternative approach, to use a per-cdc-sink, temporary, intermediate table
was considered, but this was less performant that just upserting into a common
table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/51)

cdc-sink: Add test for duplicate message delivery

---

Dockerfile
main.go

This change adds a flag to dump the git revision, golang version, and module
sources that were built into the cdc-sink binary.
Sample output:
```
cdc-sink 1bc9305-dirty
go1.16.5 amd64 darwin
github.com/cockroachdb/cdc-sink (devel)
github.com/jackc/chunkreader/v2 v2.0.1
github.com/jackc/pgconn v1.10.0
github.com/jackc/pgio v1.0.0
github.com/jackc/pgpassfile v1.0.0
github.com/jackc/pgproto3/v2 v2.1.1
github.com/jackc/pgservicefile v0.0.0-20200714003250-2b9c44734f2b
github.com/jackc/pgtype v1.8.1
github.com/jackc/pgx/v4 v4.13.0
github.com/jackc/puddle v1.1.3
github.com/pkg/errors v0.9.1
golang.org/x/crypto v0.0.0-20210711020723-a769d52b0f97
golang.org/x/net v0.0.0-20210716203947-853a461950ff
golang.org/x/text v0.3.6
```
---
This change is [<img src="https://reviewable.io/review_button.svg" …

cdc-sink: Add --version flag

---

.github/workflows/releases.yaml

This change adds a new workflow to build and push a Docker image whenever the
master branch or a semver tag is pushed. The image will be built, but not
pushed, for PR's to the master branch.
Closes #72
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/74)

cdc-sink: Add workflow to push to DockerHub.

---

.github/workflows/releases.yaml
.github/workflows/tests.yaml

This tweaks the workflow filtering for tests to allow them to run on all PRs,
regardless of the base branch. The rationale for this change is to make it
easier to build up a sequence of "stacked PRs" that depend on one another, but
that only present a single or a limited number of commits to the reviewer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/80)

workflow: Run tests on all PR base branches

---

internal/util/logfmt/logfmt.go
main.go

This change redirects the standard library logger to logrus. This is necessary
to intercept some TLS error messages emitted by the golang http server.
This change also adds an interceptor to ensure that error stack traces will be
captured in log entries as a "detail" field in the output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/81)

cdc-sink: Intercept library uses of go logger

---

internal/util/ident/ident.go
internal/util/ident/ident_test.go

This change adds an UnmarshalJSON method to all of the ident types, as well as
a test to ensure that they round-trip properly. This will support upcoming work
to support JWT-based auth.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/82)

ident: Add json unmarshalling to ident types.

---

README.md
internal/source/cdc/handler.go
internal/source/cdc/ndjson.go
internal/source/cdc/resolved.go
internal/source/cdc/webhook.go
internal/target/apply/apply.go
internal/target/apply/apply_test.go
internal/target/apply/factory.go
internal/target/apply/queries/common.tmpl
internal/target/apply/queries/conditional.tmpl
internal/target/apply/queries/delete.tmpl
internal/target/apply/queries/upsert.tmpl
internal/target/apply/templates.go
internal/target/apply/templates_test.go
internal/types/types.go

Note to reviewers: this PR is based on PR #85 (adding the request type).
This change adds the ability to use certain columns in the target table for
compare-and-set operations. That is, staged mutations will only be applied if
the proposed data has a CAS tuple that is strictly greater than the CAS tuple
of the data currently in the target table.
Additionally, certain columns can be used to impose deadlines on the
application of certain mutations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/86)

apply: Implement compare-and-set, deadlines

---

.github/workflows/tests.yaml
go.mod
go.sum
internal/target/apply/apply.go
internal/target/apply/apply_test.go
internal/target/apply/metrics.go
internal/target/apply/queries/common.tmpl
internal/target/apply/queries/conditional.tmpl
internal/target/apply/queries/delete.tmpl
internal/target/apply/queries/upsert.tmpl
internal/target/apply/templates.go
internal/target/apply/templates_test.go
internal/types/types.go
internal/util/batches/batches.go

Note to reviewers, this depends on PR #86.
This change improves the throughput of the apply package by changing the SQL to
use multi-valued VALUE clauses.
The append benchmark is updated to demonstrate the performance curve of the
Apply method at varying batch sizes.
The default batch size is adjusted to 100 to be more conservative with total
size of generated SQL.
The testing GitHub workflow is updated to run on all branches and to add
another build step for this and future benchmarks.
Benchmark results on my laptop:
```
goos: darwin
goarch: arm64
pkg: github.com/cockroachdb/cdc-sink/internal/target/apply
BenchmarkApply/size=1/base-10    	          199155	     60065 ns/op	268569.38 MB/s
BenchmarkApply/size=1/cas-10     	           76429	    161671 ns/op	38292.18 MB/s …
```

apply: Add multi-value SQL, benchmark

---

.github/docker-compose.yml
.github/workflows/tests.yaml
README.md
go.mod
go.sum
internal/cmd/pglogical/pglogical.go
internal/source/pglogical/config.go
internal/source/pglogical/conn.go
internal/source/pglogical/integration_test.go
internal/source/pglogical/metrics.go
main.go

This change adds support for consuming a postgres logical replication feed. The
general approach is to convert the feed messages into the canonical
types.Mutation message and reuse the stage-and-apply approach to keep
transaction sizes bounded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/91)

cdc-sink: Initial add of pglogical replication

---

README.md
internal/cmd/pglogical/pglogical.go
internal/source/pglogical/config.go
internal/source/pglogical/conn.go
internal/source/pglogical/integration_test.go

This changes adds a configurable, ten-second delay between restarting the
replication loop. This prevents excessive logging when, for example, there is a
schema mismatch between the source and target tables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/94)

pglogical: Add delay between retries

---

internal/target/apply/apply.go

The log message when a delete message cannot be applied due to schema drift
does not include the target table. This commit remedies that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/98)

apply: Log target table in delete drift message

---

internal/target/schemawatch/coldata.go
internal/target/schemawatch/coldata_test.go

This change makes the schema query work properly in cases where the primary key
constraint isn't named "primary". It also adds some additional test cases to
ensure that the revised query works correctly when there are secondary indexes
on the table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/103)

schemawatch: Improved PK query.

---

.github/workflows/tests.yaml

This build step will ensure that all referenced go modules will be downloaded
as part of the build. This ensures that when we send the go caches to the
GitHub workflows cache, they're complete, at least with respect to modules
used.  The GitHub cache key is based on the contents of the go.sum file and the
cache contents are only ever sent to the cache server once; you can't update an
existing cache key. This can create an opportunity for unnecessary re-downloads
if the build rules change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/96)

workflows: Add go mod download to builds

---

.github/docker-compose.yml
.github/workflows/tests.yaml
internal/source/pglogical/integration_test.go
internal/target/sinktest/integration.go

This change prepares the testing workflow for additional integration-testing
targets. An environment variable, CDC_INTEGRATION is used to selectively enable
integration tests by declaring a TestMain function in a target-specific
package.
This change also adds a no-op matrix test against MySQL 8, in preparation for
the MySQL logical-feed support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/113)

workflow: Generalize integration testing matrix

---

internal/source/pglogical/conn.go
internal/target/apply/fan/bucket.go
internal/target/apply/fan/fan_test.go

The existing code would never execute the onConsistent callback if the bucket
never becomes idle.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/114)

fan: Advance consistent point in high-rate scenario

---

internal/source/logical/chaos.go
internal/source/logical/config.go
internal/source/logical/dialect.go
internal/source/logical/logical.go
internal/source/logical/logical_test.go
internal/source/logical/metrics.go
internal/source/pglogical/config.go
internal/source/pglogical/conn.go
internal/source/pglogical/integration_test.go
internal/source/pglogical/metrics.go

This change separates the read-and-apply loop from the pglogical package. It
retains the two-goroutine approach of having a generator which connects to a
source database and an applier which drives an event-style API provided by the
logical replication loop.
When the producer routine encounters an error (e.g. a network glitch), it can
resynchronize with the upstream source and the applier via a rollback message.
This allows the least amount of disruption to any state which may be maintained
by the applier goroutine, as opposed to having to tear everything down and
restart.
The logical loop is tested by having a fake generator data source. A chaotic
wrapper around the Dialect APIs makes it easier to introduce errors throughout
the various code-paths.
---
This change is [<img …

logical: Extract base behaviors for logical replication.

---

.github/workflows/releases.yaml
.github/workflows/tests.yaml

This change updates the testing workflow only to run on pushes to master or to
a version tag.  This will eliminate the redundant testing for PRs that merge to
master. The tag format in the releases workflow is also changed to a more
conservative v-3-dots pattern.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/125)

workflow: Avoid redundant testing

---

go.mod
internal/target/apply/apply.go
internal/target/apply/apply_test.go
internal/target/apply/exponent_fix.go
internal/target/apply/exponent_fix_test.go

The pgx library doesn't like the scientific notation (e.g. "4E+2") that
Cockroach can return for DECIMAL-type columns. This patch looks for these cases
and expands them via Cockroach's own APD library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/143)

apply: Fix unparseable DECIMAL representations.

---

internal/target/apply/fan/bucket.go
internal/target/apply/fan/fan.go
internal/target/apply/fan/stamped_batch.go

The Fan.Equeue method was passing the entire slice of mutations into each call
to bucket.Enqueue. This API can actually be simplified to only accept a single
mutation at a time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/145)

fan: Avoid redundant enqueuing of mutations

---

internal/target/apply/apply.go
internal/target/apply/apply_test.go
internal/util/msort/msort.go
internal/util/msort/msort_test.go

Note to reviewers, this includes PR #145 
This change works around a CockroachDB implementation quirk wherein an UPSERT
is unable to read its own writes, which prevents the same row from being
upserted twice within the same statement. This also corrects a potential source
of data inconsistency in the applier code, if a single call to Apply contains
both upserts and deletes of the same row.
Both of the above issues can be addressed by sorting the mutations according to
their HLC time and then de-duplicating them by primary key.
The newly-added test in the apply package checks for the specific upsert
behavior, so that this workaround can be reconsidered if a future version of
CockroachDB allows duplicate rows within an UPSERT or CTE.
X-Ref: …

apply: De-duplicate applied mutations

---

.github/docker-compose.yml

This change shaves off about 30 seconds per test suite, or about 20% of the
time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/148)

workflow: Run CRDB with in-memory store.

---

internal/target/schemawatch/coldata.go
internal/target/schemawatch/coldata_test.go

It is legal to create a table with no columns. This change avoids a panic by
explicitly testing for this case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/150)

schemawatch: Handle tables with no columns.

---

internal/source/server/server.go

This change adds the system-provided pprof endpoints, to aid in runtime
debugging and profiling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/156)

server: Add pprof endpoints

---

internal/target/leases/leases.go
internal/target/leases/leases_test.go
internal/types/types.go

This change adds a new API for running exactly one instance of some named,
global task.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/151)

leases: Add leases package

---

internal/util/stdpool/stdpool.go

This code had a copy-pasto in it; the value of err in the changed lines is
always nil. This change makes the behavior obvious.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/167)

stdpool: Return nil instead of nil err variable

---

internal/source/logical/config.go
internal/source/mylogical/config.go

The change made in PR #159 dropped some CLI flags that were used only by the
mylogical package. This change restores them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/169)

mylogical: Fix missing CLI flags.

---

internal/source/server/integration_test.go
internal/source/server/provider.go
internal/source/server/test_fixture.go
internal/source/server/wire_gen.go

After discussions with the CDC team, the preferred endpoint for http based CDC
feeds should not be webhook as it is unoptimized and will throttle the outgoing
CDC feed.
This change removes the preference for testing only webhook when available and
now tests both the http and webhook endpoints.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/170)

Remove the preference for webhook in the integration tests.

---

internal/source/logical/provider.go
internal/source/server/provider.go
internal/util/stdpool/metrics.go

This change adds additional monitoring metrics for database connection pools.
Specifically, gauges are added to show the acquired, connecting, idle, and
maximum connection counts. Two new counters are added to show the cumulative
number and duration of times a caller to the pool had to wait for a new
connection to be established or returned to the pool.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/168)

stdpool: Add additional pool metrics

---

internal/source/logical/loop.go
internal/source/logical/provider.go

The loop.setConsistentPoint() method calls sync.Cond.Broadcast() outside of a
locked region. This can lead to a missed wakeup in loop.OnCommit() when running
in serial mode. The current code also has two ways to access the mutex that
guards the consistent point stamp: through the mu field as well as the
consistentPointUpdated sync.Cond.
This change moves the condition variable (and associated Locker) into the same
struct as the consistent-point stamp. It also ensures that the lock is held
when calling Broadcast().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/173)

logical: Prevent missed consistent-point notification

---

README.md

This change clarifies that the value returned by `pg_export_snapshot` is only valid for the lifetime of the session which created the snapshot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/195)

Clarify use of pg_export_snapshot

---

internal/source/logical/loop.go
internal/source/logical/provider.go

re-adding the defaultConsistentPoint in the logical package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/196)

fixing issue #193

---

.github/workflows/golang.yaml

This change simplifies the number of integration tests that are run by only
testing a single version of CockroachDB with the various logical-replication
sources. Older versions of CRDB are still tested for compatibility, but we
assume that the logical-replication source won't make a practical difference.
There is also a prepatory change to log into the GitHub Packages docker
repository, to facilitate an upcoming logical-replication source which requires
a non-trivial emulator environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/189)

workflow: Matrix testing refinements

---

README.md
internal/target/apply/apply.go
internal/target/apply/apply_test.go
internal/target/apply/conf.go
internal/target/apply/conf_test.go

This change supports document-store use cases by allowing the
otherwise-unmapped properties of incoming mutations to be stored as a JSONB
"extras" column in the target table.
Closes #194
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/199)

apply: Add support for overflow properties

---

internal/target/apply/fan/key.go
internal/target/apply/fan/key_test.go

This change tweaks how we map an incoming mutation onto a specific fan bucket
id by using the same maphash.Seed for each computation. This ensures that
mutations for the same key will be applied on the same underlying database
connection. This removes a potential source of contention in high-rate
scenarios.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/206)

fan: Make use of mapHash stable.

---

internal/target/apply/apply_test.go
internal/target/apply/queries/common.tmpl
internal/target/apply/templates.go
internal/target/apply/templates_test.go
internal/target/schemawatch/coldata.go
internal/target/schemawatch/coldata_test.go
internal/util/ident/ident.go
internal/util/ident/ident_test.go

This change adds explict support for user-defined types (e.g. enums) to the
schemawatch code. It also ensures that UDT's with mixed-case identifiers are
correctly supported.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/200)

apply: Support user-defined types with mixed-case idents.

---

internal/source/logical/config.go
internal/util/ident/flag_var.go
internal/util/ident/ident_test.go

This change allows an Ident to be used as the target of a CLI flag. It also simplifies the existing logical/config.go.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/215)

ident: Add pflag.Value adaptor

---

.github/docker-compose.yml
.github/workflows/golang.yaml

This change adds v22.2 as the primary version to test all integration cases against, and drops 20.2 from the test matrix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/245)

workflow: Test 22.2 release, drop 20.2

---

internal/source/cdc/config.go
internal/source/cdc/ndjson.go

The default Scanner buffer used for ndjson parsing is 64k. This per-line limit can be hit if the source cluster sends data with blobs. This change allows the buffer size to be set to arbitrary values.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/273)

cdc: Make bufio.Scanner buffer configurable

---

internal/source/cdc/handler_test.go
internal/source/cdc/resolver.go

This change reorganizes the code in the readInto() method into an outer method that loops and an inner method which implements a single pass of the loop. This change is motivated by a desire to clarify the lifetime of the next-timestamp transaction associated with an iteration of the resolver loop.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/289)

cdc: Split resolver.readInto()

---

internal/source/cdc/provider.go
internal/source/cdc/resolved_stamp.go
internal/source/cdc/resolver.go
internal/source/cdc/resolver_test.go
internal/source/cdc/test_fixture.go
internal/source/cdc/wire_gen.go
internal/source/server/injector.go
internal/source/server/test_fixture.go
internal/source/server/wire_gen.go
internal/target/leases/leases.go
internal/target/leases/leases_test.go
internal/target/leases/provider.go
internal/types/types.go
internal/util/retry/retry.go

The locks created by a SELECT FOR UPDATE command are unreplicated and fragile if the leaseholder for the associated range is moved. This change creates an explicit lease for the destination schema to work around the limitation.
https://github.com/cockroachdb/cockroach/issues/100194
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/297)

cdc: Use lease package when retrieving work

---

internal/target/apply/fan/bucket.go
internal/target/apply/fan/stamped_batch.go
internal/target/apply/fan/stamped_batch_test.go

This change calculates the mutation weight of a stampedBatch once and updates it as any batch coalescing occurs. An environment variable, STAMPED_BATCH_CHECKS, is added for temporary testing purposes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/298)

fan: Add sanity-check for semaphore over-relase

---

internal/source/logical/chaos.go
internal/source/logical/logical_test.go
internal/source/logical/loop.go
internal/target/leases/leases.go
internal/target/leases/leases_test.go
internal/types/types.go

This change allows the lease package to report when a blocking lease will expire.  The logical loop code will now use that to optimize its waiting behaviors. The chaos dialect also now simulates busy-lease and error conditions when acquiring a lease.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/304)

leases: Report blocked-until time

---

.github/docker-compose.yml
.github/workflows/golang.yaml

This change adds 23.1 to the test matrix, with the caveat that there's no "latest" tag in the unstable repo.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/305)

workflow: Add CockroachDB v23.1b2 to test matrix

---

internal/target/schemawatch/coldata_test.go
internal/target/schemawatch/watcher.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/306)

schemawatch: only return actual tables, not views, when querying table names

---

.github/workflows/golang.yaml
internal/target/apply/apply_test.go

The flakiness in `apply_test.go` against v23.1 is caused by a performance regression in the table metadata queries.  This PR creates a fresh database for each loop of the test. There's a separate commit which tweaks how the go test logs are emitted to the GitHub Actions UI.
https://github.com/cockroachdb/cockroach/issues/102259
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/314)

Resolve v23.1 test flakes

---

.github/workflows/golang.yaml
internal/source/cdc/handler_test.go
internal/source/cdc/resolved_stamp.go
internal/source/cdc/resolver.go
internal/source/cdc/resolver_test.go
internal/source/server/integration_test.go
internal/util/stamp/queue.go

These changes remove the remnants of the `SELECT FOR UPDATE` approach to locking. They also add a test for concurrent instances of the resolver loop. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/315)

Remove unnecessary locking code from resolver

---

internal/source/cdc/resolved.go
internal/source/cdc/url_test.go

The timestamp parsing code has always thrown away the nanos values. A test is added to check for correct parsing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/319)

cdc: Fix timestamp parsing

---

Dockerfile
go.mod
go.sum
internal/target/sinktest/sinktest.go

This change updates the build environment to use go 1.20. The staticcheck and lint tools are updated to fix compatibility issues. The sinktest.go file is updated to remove a check failure about calling the global rand.Seed method.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/321)

cdc-sink: Build with go 1.20

---

go.mod
go.sum
internal/source/cdc/resolver.go
internal/source/fslogical/config.go
internal/source/fslogical/fslogical.go
internal/source/fslogical/integration_test.go
internal/source/fslogical/provider.go
internal/source/fslogical/tombstones.go
internal/source/fslogical/wire_gen.go
internal/source/logical/chaos.go
internal/source/logical/dialect.go
internal/source/logical/factory.go
internal/source/logical/fan_events.go
internal/source/logical/fan_workers.go
internal/source/logical/generator_test.go
internal/source/logical/loop.go
internal/source/logical/ordered_events.go
internal/source/logical/provider.go
internal/source/logical/serial_events.go
internal/source/mylogical/conn.go
internal/source/pglogical/conn.go
internal/util/stopper/stopper.go
internal/util/stopper/stopper_test.go

This change adds a stopper utility package to assist with gracefully
transitioning a Dialect from backfill to transactional modes. The API is very
much like an errgroup, in that it starts some number of goroutines, however the
associated context is canceled after the Stop() method is called and the
goroutines have exited. The existing logical-loop code uses normal context
cancellation to signal a need to change modes, but this winds up being too
coarse-grained, we want the dialect's message producer to exit and for the
message consumer to drain the channel.
The logical.Event interface gains an explicit Flush() method to allow all
in-flight mutations passed to OnData() to be written to the backing store. This
further simplifies FK-preserving backfill mode, since we no longer attempt to …

logical: Improve graceful draining

---

internal/source/logical/factory.go
internal/source/logical/fan_workers.go
internal/source/logical/loop.go
internal/target/apply/conf.go
internal/target/apply/provider.go
internal/target/schemawatch/watcher.go
internal/target/schemawatch/watcher_test.go

Condition variables are hard to use well in non-trivial locking and flow control. This change replaces the uses of sync.Cond with channels that are closed to indicate that some state has been invalidated and needs to be refreshed. This pattern plays nicely with RWMutex as long as the data and its associated channel are read from the locked data within the same critical region.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/329)

Replace use of sync.Cond with channel

---

.github/workflows/binaries.yaml

Remove unnecessary now-unnecessary input from workflow_dispatch action.
Authenticate to GCP first, since this is likely the most fragile step.
Remove uploading artifacts to GitHub, since the summaries link directly to the
tarballs.
Use either "cdc-sink" or "cdc-sink.exe" as the executable name in the tarball.
Suppress warning about .gcloudignore file, since we're not globbing uploads.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/333)

workflows: Minor cleanups to push workflow

---

.github/docker-compose.yml
.github/workflows/golang.yaml

This change switches the 23.1 test image to the stable release tags in DockerHub. It also bumps the primary test version to 23.1.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/334)

workflow: Use CockroachDB 23.1 public releases

---

.github/workflows/status.yaml

This builds on the previous change to create a pending status object for any given workflow.  This improves the GitHub UI experience, to show that, eventually, a status update will occur.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/355)

workflow: Create pending status objects for workflows

---

.github/workflows/binaries.yaml
.github/workflows/golang.yaml

This change triggers the golang and binary workflows for merge queue actions. The binary-build workflow is tweaked to only copy files out to the storage bucket for push or manual-run events.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/356)

workflow: Changes for merge queue

---

.github/workflows/dependabot.yaml

This workflow will mark all PRs by Dependabot as approved and add them to the queue. The build queue will naturally reject any PRs that cause the tests to fail.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/357)

workflow: Enable automatic Dependabot

---

.github/workflows/binaries.yaml
.github/workflows/docker.yaml
.github/workflows/golang.yaml

If a branch is pushed several times in quick succession, this change will ensure that outdated workflow runs are canceled immediately.
https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/359)

workflow: Cancel outdated workflow runs

---

.github/workflows/binaries.yaml

This change makes the auth-and-push behavior conditional on the presence of the GCP secret. This is necessary to allow Dependabot's PRs to preflight correctly, since they exist on a fork which does not have access to the secret.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/363)

workflow: Don't authenticate to GCP if secret is unset

---

.github/workflows/dependabot.yaml

This change makes the last step in the auto-Dependabot workflow functional for Golang dependencies.  I verified the `gh` step with a previous PR to ensure that the dependencies changes will flow through.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/364)

workflow: Enable final auto-merge behavior for gomod

---

internal/script/provider.go
internal/script/script.go
internal/script/script_test.go
internal/sinktest/all/fixture.go
internal/sinktest/all/wire_gen.go
internal/source/fslogical/wire_gen.go
internal/source/logical/wire_gen.go
internal/source/mylogical/wire_gen.go
internal/source/pglogical/wire_gen.go
internal/source/server/provider.go
internal/source/server/wire_gen.go
internal/staging/applycfg/conf.go
internal/staging/applycfg/conf_test.go
internal/staging/applycfg/configs.go
internal/staging/applycfg/configs_test.go
internal/staging/applycfg/provider.go
internal/target/apply/apply.go
internal/target/apply/apply_test.go
internal/target/apply/debug.go
internal/target/apply/factory.go
internal/target/apply/provider.go
internal/target/apply/templates.go
internal/target/apply/templates_test.go

This change moves the persistence code for apply.Config under the staging package, since we're making the command-and-control tables separate from the target tables.
There are no functional changes in this commit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/374)

apply: Extract config persistence code

---

.github/workflows/golang.yaml
internal/source/pglogical/conn.go

This change adds go vet to the static checks and removes a line of unreachable code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/376)

workflow: Run go vet tool

---

.github/workflows/binaries.yaml
.github/workflows/golang.yaml

The SHA under test is not always necessarily the same as the commit that the PR is attached to. This split seems to happen with PRs that come from forks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/384)

workflow: Push status check to PR head sha

---

.github/workflows/golang.yaml

We use the merge queue to admit changes, so there's no need to re-test once the commit hits a destination branch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/385)

workflow: Don't test on push

---

internal/source/mylogical/conn.go

MySQL community editions do not have MySQL in the name - they use "Source Distribution" again apparently.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/398)

mylogical: allow "Source Distribution" to map flavor to MySQL

---

internal/sinktest/all/fixture.go
internal/sinktest/all/wire_gen.go
internal/source/fslogical/injector.go
internal/source/fslogical/wire_gen.go
internal/source/logical/provider.go
internal/source/logical/wire_gen.go
internal/source/mylogical/wire_gen.go
internal/source/pglogical/wire_gen.go
internal/staging/version/provider.go
internal/staging/version/version_test.go
internal/staging/version/versions.go

This change introduces a utility class that provides useful warning messages when making breaking changes to the cdc-sink schema.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/400)

version: Detect incompatible metadata schema changes

---

internal/sinktest/base/provider.go
internal/sinktest/base/table_info.go
internal/target/schemawatch/coldata.go
internal/target/schemawatch/coldata_test.go
internal/target/schemawatch/dependencies.go
internal/target/schemawatch/dependencies_test.go
internal/target/schemawatch/watcher.go
internal/target/schemawatch/watcher_test.go

This change updates the schemawatch package to support Oracle as the target database.
The tests in the schemawatch package will pass if given the flag `-testTarget oracle://system:SoupOrSecret@127.0.0.1:1521/XEPDB1`. These tests won't be enabled in the CI system until the apply package has been ported.
The base.ProvideTestDB() function has been updated to create a new SQL user, thereby creating a new schema for creating tables into. The names of testing tables have changed to support both PG and Oracle naming conventions.
The delta is coldata_test.go is driven by wanting to keep the same test code running for multiple products. Similarly, the table-dependency test uses such trivial tables, it happens to work for both databases with a trivial change.
h/t: @BramGruneir for initial research …

schemawatch: Initial Oracle implementation

---

internal/util/cmap/cmap.go
internal/util/cmap/cmap_test.go
internal/util/cmap/equal.go
internal/util/cmap/equal_test.go
internal/util/cmap/identity.go
internal/util/cmap/identity_test.go

This package contains a Map implementation where the keys aren't required to be comparable.  Instead, the Map has a mapper function which converts a key into a comparable representation that is used to locate a value.
The motivation for this change is to readily support case-preserving, but case-insentivite identifier mappings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/417)

cmap: Add utility for canonicalized mappings

---

internal/cmd/preflight/preflight.go
main.go

This new command will check if stagingConn and/or targetConn databases can be reached.  Ideally, the same flags on the command needed to start cdc-sink should work directly with this command, but only those two flags are checked.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/420)

Adds preflight command

---

.github/workflows/binaries.yaml
.github/workflows/golang.yaml

We've been seeing some build failures due the upstream go modules cache
rate-limiting our HTTP requests. This change adds a job to pre-warm the local
setup-go cache, instead of allowing each component of the test matrix to
download modules independently.
This change also removes a few build steps related to computing the setup-go
cache key, since caching is the default mode in v4.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/427)

workflow: Pre-warm go module cache

---

internal/util/ident/schema.go
internal/util/ident/schema_test.go

This change updates the behavior of Schema.Contains() so that a schema "db" will return true for a table "db.public.tbl".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/428)

ident: Schema.Contains fix for nested namespaces

---

internal/target/apply/apply.go

Previously, `target` gets shadowed, meaning the error message prints a blank and unhelpful `target` database as it is missing. Fix this by removing the shadowing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/438)

apply: fix error message for missing target tables

---

internal/source/mylogical/conn.go
internal/target/apply/apply_test.go
internal/target/apply/queries/pg/common.tmpl
internal/target/apply/templates.go
internal/target/apply/templates_test.go
internal/target/schemawatch/coldata.go
internal/target/schemawatch/coldata_test.go
internal/types/types.go
internal/util/ident/ident_test.go
internal/util/ident/parse_test.go
internal/util/ident/udt.go
internal/util/ident/udt_test.go

Arrays of UDT enums were under-tested. Adding tests revealed a number of
deficiencies in how enum types were being represented in the schemawatch
package.
Until we decide to implement a proper typesystem model, this change adds an
array field to the ident.UDT type. It also changes ColData.Type to a string,
since we really only ever need to send the column type back to the target
database after introspecting it. This has a minor knock-on effect in the
mylogical package, although that code only ever looks at the ColData.Type field
for a sentinel value.
A small tweak has been made to the pg template to overcome a limitation in the
pgx driver, where the type information for the array-of-enum isn't always
loaded by the time we want to send the enum values. The substitution parameter
is first …

target: Fix edge cases in UDT enum arrays

---

internal/sinktest/base/provider.go
internal/source/cdc/resolver.go
internal/source/logical/generator_test.go
internal/source/logical/logical_test.go
internal/staging/leases/leases_test.go
internal/staging/stage/stage_test.go
internal/target/apply/apply_test.go

This change uses the newer atomic value types for improved ergonomics (e.g. atomic.Bool instead of swapping zero and one).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/442)

internal: Use newer sync/atomic APIs

---

.github/workflows/binaries.yaml
.github/workflows/codeql.yaml
.github/workflows/golang.yaml
.github/workflows/warm-build-cache.yaml
internal/script/loader.go
internal/source/cdc/handler.go
internal/staging/leases/leases.go

This change adds GitHub CodeQL security checks to the build. It also corrects a
small number of issues that were detected. These checks will be run for pull
requests and pushes to the master branch.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/441)

workflow: Add GitHub CodeQL security checks

---

.github/workflows/golang.yaml
internal/source/cdc/config.go

PR #439 had a bad merge hunk which keeps the binary from starting. This change also adds a check to ensure that the main entry point starts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/451)

cdc: Fix flag panic due to bad merge

---

internal/source/logical/fan_workers.go
internal/source/logical/logical_test.go

The fslogical frontend will experience a stall if a nested collection is being processed in backfill mode and a mutation cannot be applied. This is because the Flush() method waits on a counter condition variable that would never be decremented.
This change ensures that the decrement always happens by hoisting the guts of the loop() method into a closure and calling the decrement API via defer.
Testing for this condition is performed by plumbing the choas probability into fanWorkers to simulate the applier failing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/449)

logical: Fix stall if apply fails in nested backfill mode

---

.github/workflows/docker.yaml
Dockerfile

This change makes the builder image run using the host platform, rather than
being run under emulation. This drops the docker build time from 20 minutes to
4.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/452)

Docker: Faster cross-compile setup

---

internal/source/logical/fan_workers.go
internal/source/logical/generator_test.go
internal/source/logical/logical_test.go

The fanWorkers.Flush() method had no way to report errors encountered by concurrent worker goroutines. This change adds a flag to the fanWorkers mutex state to indicate that a loop goroutine has exited. If a loop worker has exited, we know that the errgroup that's managing the other goroutines will report that error.
Additionally, the logical_test.go hadn't kept up with all modes that a logical loop can be configured for (e.g. foreign keys). This change ensures that FK modes are covered.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/454)

logical: Detect concurrent loop errors in fanWorkers

---

.github/codecov.yml

This change adds a codecov.yml file to make the codecov reports more actionable. It also adds a flag to enable line-by-line reporting via GitHub code annotations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/455)

codecov: Ignore generated files

---

internal/target/schemawatch/coldata.go
internal/target/schemawatch/coldata_test.go

The code in PR #450 attempted to homogenize the column default expressions. The testing was insufficint and only looked at constant default expressions. The string trimming would lose any trailing parentheses in more complex expressions.
This change no longer tries to remove the varying type assertions that we might see in CockroachDB and PostgreSQL and updates the tests to be more permissive about expected values.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/456)

schemawatch: Don't trim default expressions

---

.github/workflows/warm-build-cache.yaml

This change only runs the pre-build steps when there was a cache miss; actions caches are immutable once created, so there's never a point in trying to refresh.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/460)

workflow: Decrease duplicate effort when warming build cache

---

internal/cmd/fslogical/fslogical.go
internal/cmd/fslogical/fslogical_test.go
internal/cmd/mylogical/mylogical.go
internal/cmd/mylogical/mylogical_test.go
internal/cmd/pglogical/pglogical_test.go
internal/cmd/start/start.go
internal/cmd/start/start_test.go
internal/source/fslogical/fslogical.go
internal/source/fslogical/injector.go
internal/source/fslogical/wire_gen.go
internal/source/mylogical/mylogical.go
internal/source/mylogical/wire_gen.go
internal/source/pglogical/injector.go
internal/source/pglogical/pglogical.go
internal/source/pglogical/wire_gen.go
internal/source/server/integration_test.go
internal/source/server/provider.go
internal/source/server/server.go
internal/source/server/wire_gen.go
internal/types/types.go
internal/util/stdlogical/stdlogical.go
internal/util/stdlogical/stdlogical_test.go

This change extracts the heavily-duplicated code in the fslogical, mylogical, pglogical, and start commands into a common stdlogical package.
Notable changes:
- We can now test that the CLI flag binding code runs to completion.
- The binary buildinfo is logged on startup.
- The CDC server may run the diags server on a separate port.
Closes #117
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/457)

cmd: Unify logical commands

---

.github/workflows/warm-build-cache.yaml

We've been seeing unexpected cancellation of the cache-warming workflow. This
change moves the concurrency block from the job up to the workflow itself and
explicitly sets cancel-in-progress to false to see if that solves the problem.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/463)

workflow: Fix spontaneous cancellation of cache warming workflow

---

internal/source/mylogical/conn.go

Depending on how MySQL is shipped, it can show up as `Homebrew` or `Source distribution` without `MySQL` actually being in the string. As such, relax the `@@version_comment` check to allow anything.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/462)

mylogical: relax @@version_comment check

---

internal/source/fslogical/fslogical.go
internal/source/fslogical/integration_test.go
internal/source/fslogical/provider.go
internal/source/logical/config.go
internal/source/logical/loop.go
internal/source/pglogical/config.go

The firestore.DocumentID sentinel usually works correctly with the values that one might expect to find in `doc.Ref.ID` when querying single collections. However, when querying collection groups, that value needs to be more (globally) unique, since the same document ID can, in theory, exist within multiple collection groups that are being queried.
This change removes a misguided attempt at solving for this, with a new understanding of how this sentinel behaves. Reference URLs are included in the docstring on `Dialect.backfillPoint()`.
The previous code was, in effect, randomly sampling swathes of document ids, while the test code only checked that we arrived at the desired number of rows in the target tables. In order to verify that ID-based pagination is working correctly, all documents …

fslogical: Fix backfill pagination

---

.github/workflows/go-binaries.yaml
.github/workflows/go-build-cache.yaml
.github/workflows/go-codeql.yaml
.github/workflows/go-docker.yaml
.github/workflows/go-tests.yaml
.github/workflows/go.yaml

Using a concurrency group in a called workflow (i.e. to only warm the go build
cache once) is still showing spontaneous cancellation by the actions platform.
This change rolls all workflows up into a single dispatch event, triggered by a
top-level workflow. The top-level go.yaml then calls the existing, albeit
renamed, workflows after the cache warming has taken place.
An upside to this approach is that there's a relatively simple workflow that
provides a high-level view of the build, while the details of the build can
still be grouped into separate files.
Conditional behaviors, such as pushing to DockerHub or to the GCP bucket, have
been made inputs of their respective workflows, again to make it obvious at the
outset what happens when.
Where applicable, the `${{ !cancelled()}}` idiom is …

workflow: Rearrange the deck chairs

---

internal/sinktest/all/wire_gen.go
internal/sinktest/base/provider.go
internal/sinktest/base/wire_gen.go
internal/target/schemawatch/coldata.go
internal/target/schemawatch/coldata_test.go
internal/target/schemawatch/dependencies.go
internal/target/schemawatch/watcher_test.go

This change ports the schema introspection queries from using
CockroachDB-specific porcelain to using the information_schema virtual tables.
The existing table-dependency query is still used for older versions of
CockroachDB that enter an infinite loop when executing the revised CTE.
The test fixture code adds a workaround for the lack of cross-database
information_schema queries by swapping out the underlying database connection
after we've performed a `CREATE DATABASE`.
The schemawatch tests will pass against PostgreSQL v11-v15 by setting
`TEST_TARGET_CONNECT=postgres://postgres:SoupOrSecret@127.0.0.1:5432`
CI testing using PostgreSQL as a target will not be enabled until the apply
package is updated.
X-Ref: #430
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …

schemawatch: Support vanilla PostgreSQL

---

internal/source/cdc/config.go
internal/source/cdc/resolver.go

This change adds a new configuration value that allows staged data to be retained after it has been applied. This could be used to allow resolved timestamps to be unwound and re-applied or to perform post-hoc analysis of what was staged versus what was applied.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/472)

cdc: Allow staged data to be retained for longer

---

.github/workflows/go-wiki.yaml
.github/workflows/go.yaml

This change brings the wiki-maintenance workflow into the unified golang workflow. This allows the workflow to take advantage of the cache-warming behavior.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/473)

workflow: Move wiki maintenance into main workflow

---

.github/workflows/go-tests.yaml
internal/sinktest/base/provider.go
internal/target/apply/apply_test.go
internal/target/apply/queries/crdb/common.tmpl
internal/target/apply/queries/crdb/conditional.tmpl
internal/target/apply/queries/crdb/delete.tmpl
internal/target/apply/queries/crdb/upsert.tmpl
internal/target/apply/queries/pg/upsert.tmpl
internal/target/apply/templates.go
internal/target/apply/templates_test.go
internal/target/apply/testdata/crdb/base.delete.sql
internal/target/apply/testdata/crdb/base.upsert.sql
internal/target/apply/testdata/crdb/cas.delete.sql
internal/target/apply/testdata/crdb/cas.upsert.sql
internal/target/apply/testdata/crdb/casDeadline.delete.sql
internal/target/apply/testdata/crdb/casDeadline.upsert.sql
internal/target/apply/testdata/crdb/deadline.delete.sql
internal/target/apply/testdata/crdb/deadline.upsert.sql
internal/target/apply/testdata/crdb/expr.delete.sql
internal/target/apply/testdata/crdb/expr.upsert.sql
internal/target/apply/testdata/crdb/ignore.delete.sql
internal/target/apply/testdata/crdb/ignore.upsert.sql
internal/target/apply/testdata/crdb/source_names.delete.sql
internal/target/apply/testdata/crdb/source_names.upsert.sql
internal/target/apply/testdata/pg/base.upsert.sql
internal/target/apply/testdata/pg/casDeadline.upsert.sql
internal/target/apply/testdata/pg/expr.upsert.sql
internal/target/apply/testdata/pg/ignore.upsert.sql
internal/target/apply/testdata/pg/source_names.upsert.sql
internal/util/stdpool/timeout.go

This change adds support to the apply package for applying mutations to a
PostgreSQL database. It also enables CI testing for PostgreSQL v11 through v15.
Review notes:
- The primary change required is to use INSERT ON CONFLICT DO UPDATE instead of
the CockroachDB-specific UPSERT command. One note here is that CockroachDB
does not allow the ROW keyword when performing a multi-column update, whereas
PostgreSQL requires it.
- The golden-output template tests now compare CRDB vs. PG.
- ProvideTargetSchema() updates the TargetPool's connection string. This value
is used by logical-loop tests to create their own connection pool.
- The idle_in_transaction_session_timeout connection variable must be set to an
integer number of milliseconds in earlier version of PostgreSQL.
X-Ref: …

apply: Add support for PostgreSQL

---

internal/source/cdc/handler.go
internal/source/cdc/handler_test.go
internal/source/cdc/immediate.go
internal/source/cdc/ndjson.go
internal/source/cdc/provider.go
internal/source/cdc/resolver.go
internal/source/cdc/script_helpers.go
internal/source/cdc/testdata/main.ts
internal/source/cdc/webhook.go
internal/source/cdc/webhook_query.go
internal/source/cdc/wire_gen.go
internal/source/logical/dialect.go
internal/source/logical/factory.go
internal/source/logical/fake_dialect.go
internal/source/logical/script_events.go
internal/source/server/wire_gen.go

Note that this is stacked on PR #477 
This change unifies the processing for immediate-mode CDC feeds with the
existing logical loop pipeline. This will ensure that immediate-mode payloads
can use all facilities available to logical loops. Tests for userscript
integration are added to verify that the script is invoke in both immediate and
deferred modes.
The logical package is updated to allow the immediate-mode HTTP handler to make
use of the mutation pipeline. A fake loop is constructed and the event handler
is extracted.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/478)

cdc: Fully integrate with userscript

---

internal/script/meta.go
internal/script/script.go
internal/sinktest/scripttest/scripttest.go
internal/sinktest/scripttest/testdata/logical_test.ts
internal/source/cdc/handler_test.go
internal/source/cdc/ndjson.go
internal/source/cdc/resolver.go
internal/source/cdc/webhook.go
internal/source/mylogical/conn.go
internal/source/mylogical/integration_test.go
internal/source/pglogical/conn.go
internal/source/pglogical/integration_test.go

This is a follow-up to #478 which aligns the behaviors in the `pglogical` and `mylogical` packages with the script wiring in the `cdc` package. Some common test code is extracted from the `cdc` package into a `sinktest/scripttest` helper package.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/488)

Userscript integration for xylogical packages

---

internal/sinktest/all/wire_gen.go
internal/sinktest/base/provider.go
internal/sinktest/base/wire_gen.go
internal/source/cdc/test_fixture.go
internal/source/cdc/wire_gen.go
internal/source/fslogical/injector.go
internal/source/fslogical/wire_gen.go
internal/source/logical/config.go
internal/source/logical/logical_test.go
internal/source/logical/provider.go
internal/source/logical/wire_gen.go
internal/source/mylogical/wire_gen.go
internal/source/pglogical/wire_gen.go
internal/source/server/wire_gen.go
internal/target/apply/apply.go
internal/target/apply/factory.go
internal/target/apply/metrics.go
internal/target/apply/provider.go
internal/target/apply/templates.go
internal/types/types.go
internal/util/stmtcache/metrics.go
internal/util/stmtcache/stmtcache.go

This change adds prepared statements to the apply package to support targets
that don't use the pgx library. pgx automatically retains prepared statements
without user intervention, so this was never necessary before.
This measurably improves throughput when using Oracle Database as a target and
would be useful for other targets in the future. This change also identified a
dependency issue in some of the test rigs, where the Appliers and Watchers were
attached to the bootstrap stack instead of the per-test stack. This led to
cross sql.DB use between prepared statements.
Since we have a cache around prepared statement, the apply template code no
longer has its own cache of SQL expressions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

apply: Use prepared statements in the hot path

---

internal/source/cdc/handler_test.go
internal/source/cdc/provider.go
internal/source/cdc/resolved.go
internal/source/cdc/resolver.go
internal/source/cdc/resolver_test.go

The resolver.loop field is unnecessary. A reference to the logical.Loop is implicitly available via the Dialect API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/496)

cdc: Remove resolver.loop field

---

internal/source/cdc/resolver.go

This adds a useful error message if the target schema exists, but has no tables in it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/501)

cdc: Add sanity-preserving error message if no tables

---

go.mod
go.sum
internal/util/stdpool/ora.go

The updated go-ora version provides an API to create a connector without making a throw-away call to sql.Open() and spying on the sql.Driver instance.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/503)

stdpool: Use NewConnector API in go-ora 2.7.18

---

go.sum
internal/sinktest/base/provider.go
internal/target/schemawatch/coldata.go
internal/target/schemawatch/coldata_test.go
internal/target/schemawatch/dependencies.go
internal/target/schemawatch/dependencies_test.go
internal/target/schemawatch/parse_helpers.go
internal/target/schemawatch/watcher.go
internal/target/schemawatch/watcher_test.go
internal/types/product_string.go
internal/types/types.go
internal/util/stdpool/my.go
internal/util/stdpool/target.go

This is the initial work to support mysql as a target, focusing on getting the schema information. 
Subsequent PRs will address the logic to apply mutations and  completing the backed connection support (with TLS, and better error handling).
Summary of changes:
- Added mysql connection pool. Not supporting TLS yet.
- Added templates for querying column information and constraint dependencies.
- Updated dependencies test to be compatible with mysql syntax.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/506)

mysql target: getting schema information from database

---

internal/source/logical/logical_test.go
internal/source/logical/script_events.go

There is a bug in the current flow where a delete mutation can be sent to a userscript table's map function if there is no dispatch function defined on the source. There is no data in a deletion to map, so the operation doesn't make sense and the function binding returns an error as there is no payload.
This change reworks scriptEvents.OnData() so that any configuration of dispatch, map, etc. have the same flow.
Fixes #507
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/513)

logical: Fix deletes sent to userscript map function

---

internal/cmd/dumptemplates/dumptemplates.go
internal/target/apply/templates.go
internal/target/apply/templates_test.go
internal/util/fscopy/fscopy.go
internal/util/fscopy/fscopy_test.go
internal/util/fscopy/testdata/a/b/c/hello.txt
main.go

This change adds an environment variable that allows the golang templates to be loaded from the filesystem, instead of using the ones embedded in the binary. A hidden `cdc-sink dumptemplates` command is added to copy the templates to disk.
The indended use-case for this change is to support in-the-field adjuments to the query templates, without the need to recompile the binary. No long-term compatibility guarantees can be made about the contents and structure of the template files, since they are tightly coupled with internal cdc-sink datastructures.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/515)

apply: Allow templates to be loaded from disk

---

internal/staging/stage/factory.go
internal/staging/stage/gzip.go
internal/staging/stage/gzip_test.go
internal/staging/stage/stage.go
internal/staging/stage/stage_test.go
internal/types/types.go

This change is part of #487 to support three-way merges. It adds a before field to types.Mutation and allows this data to be persisted.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/517)

stage: Support storing a Mutation.Before field

---

internal/target/apply/apply.go
internal/target/schemawatch/parse_helpers.go
internal/target/schemawatch/parse_helpers_test.go
internal/types/types.go

Changing the ColData.Parse to accept any type, rather than strings.
The MySQL driver wants serializable json, this change allows the apply logic to call a custom parser that serializes the internal json object before it is sent to the driver.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/522)

apply: make the parser helper more generic.

---

go.mod
go.sum

The workaround that was introduced in PR #508 has been upstreamed. This change removes the local override and bumps the go-ora version.
X-Ref: https://github.com/sijms/go-ora/pull/445
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/532)

oracle: Use upstream go-ora

---

internal/sinktest/base/provider.go
internal/source/cdc/request.go
internal/source/cdc/url_test.go
internal/source/mylogical/integration_test.go
internal/source/pglogical/integration_test.go
internal/target/schemawatch/watcher.go

This change updates the CreateTable and CreateSchema functions to generate
names that contain dashes. This helps to ensure that all identifiers are
correctly quoted when we generate SQL commands.
This change additionally corrects some test failures around parsing ndjson URLs
that contain dashes. There is also a correction made to a schema introspection
query that was not correctly using a quoted ident type. There are a few
naming-related changes in the pglogical and mylogical packages, which are
explained by surrounding comments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/538)

sinktest: Generate names that must be quoted

---

internal/sinktest/all/fixture.go
internal/sinktest/all/provider.go
internal/sinktest/all/wire_gen.go
internal/target/dlq/config.go
internal/target/dlq/dlq.go
internal/target/dlq/dlq_schema.go
internal/target/dlq/dlq_test.go
internal/target/dlq/provider.go
internal/types/types.go

Review notes: This is being sent in parallel to #540, which will only need a minor PR to call this API when they're both added. If we decide that cdc-sink should create schemas in the target data (why not is outlined below), we already have known-usable schemas in this PR for testing.
This change is part of #487 to support three-way merges.
This change adds, but does not integrate, support for a per-target-schema DLQ. cdc-sink, as a design rule, does not perform any schema changes in the target database. If the user wants to use the DLQ, they will need to create the destination table. The only requirements on the DLQ table are that it contain certain well-known column names with appropriate types. A basic schema is suggested by cdc-sink, and this suggested schema is used by the DLQ tests. …

dlq: Add dead-letter queue package

---

.github/workflows/crdb-key-lint.yaml

This change adds a workflow that runs on push to look for strings that appear to be CockroachDB license keys.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/548)

workflow: Add a simple linter for CockroachDB license keys

---

internal/sinktest/all/wire_gen.go
internal/source/cdc/wire_gen.go
internal/source/fslogical/wire_gen.go
internal/source/logical/config.go
internal/source/logical/provider.go
internal/source/logical/wire_gen.go
internal/source/mylogical/wire_gen.go
internal/source/pglogical/wire_gen.go
internal/source/server/wire_gen.go
internal/target/apply/apply.go
internal/target/apply/apply_test.go
internal/target/apply/factory.go
internal/target/apply/provider.go

This change is part of #487 to support three-way merges.
PR #540 and #543 were submitted separately, so the apply code did not support writing to the DLQ. This change completes the wiring and allows conflicts to be written to the queue.
The unexported apply.newApply() function was made a method on the factory type, to decrease the number of arguments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/546)

apply: Finish DLQ wiring

---

internal/script/loader.go
internal/script/provider.go
internal/script/script.go
internal/script/script_test.go
internal/script/testdata/cdc-sink@v1.d.ts
internal/script/testdata/main.ts
internal/target/apply/apply.go
internal/target/apply/apply_test.go
internal/util/ident/map.go
internal/util/ident/map_test.go
internal/util/merge/merge.go
internal/util/merge/standard.go
internal/util/merge/standard_test.go

This change adds merge.Standard and exposes it to the userscript. The merge function identifies the properties which have changed between the before and proposed bags. If the value of the property in the before bag equals the value of the property in the target, the change is applied.
Property equivalency is presently defined as "serializes to the same JSON bytes". The golang json serializer is deterministic and we have a rather fluid typesystem, so this seems like a reasonable initial implementation.
A fallback merge function can be composed with merge.Standard to handle properties with application-specific semantics. The script test shows the composition of the standard merge with a counter-like field that is only ever incremented. Properties which cannot be automatically merged are …

merge: Implement a standard merge function

---

.github/workflows/go-tests.yaml
internal/cmd/preflight/preflight.go
internal/script/script_test.go
internal/sinktest/base/provider.go
internal/source/cdc/request.go
internal/source/logical/logical_test.go
internal/target/apply/apply_test.go
internal/target/apply/templates.go
internal/target/dlq/dlq.go
internal/target/dlq/dlq_schema.go
internal/target/schemawatch/coldata.go
internal/target/schemawatch/coldata_test.go
internal/target/schemawatch/dependencies.go
internal/target/schemawatch/dependencies_test.go
internal/target/schemawatch/parse_helpers.go
internal/target/schemawatch/watcher.go
internal/target/schemawatch/watcher_test.go
internal/types/product_string.go
internal/types/product_test.go
internal/types/types.go
internal/util/stdpool/my.go

Adding a new product type to handle the differences between MySQL and MariaDB.
Summary of differences:
- JSON type is a synonym for longtext with check constraint. The code to get schema information is now specific to MariaDB to correctly detect JSON columns.
- Spatial information in the apply_test requires custom handling.
- Default expressions are stored in a different format than mySQL in the information schema. For instance, absence of a default expression is represented by a 'NULL' string rather that a NULL value
Fixes #552 .
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/551)

mariadb: support for target database.

---

internal/script/loader.go
internal/script/provider.go
internal/script/script.go
internal/script/script_test.go

This change fixes two bugs in the script package. Firstly, if the `script.Evaluate()` function is called more than once (as it is when multiple logical loops are started), the UserScript instances that are created share a common goja.Runtime object, but have separate mutexes to guard access to the runtime. This changes the script loader (which constructs the Runtime) to also allocate a shared mutex which is passed to the derived UserScript instance(s).
There is also a small fix to `bindMap()` where a mutation's Before field was not being propagated. A test is added to verify the fix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/566)

script: Fix race condition and missing Before in UserScript

---

internal/sinktest/scripttest/scripttest.go
internal/util/subfs/subfs.go

This change extracts a util/subfs package to support an upcoming PR that makes use of the same functionality outside of test code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/567)

subfs: Extract SubstitutingFS from scripttest package

---

internal/source/cdc/handler_test.go
internal/source/fslogical/integration_test.go
internal/source/logical/config.go
internal/source/logical/logical_test.go
internal/source/logical/loop.go
internal/source/mylogical/integration_test.go
internal/source/pglogical/integration_test.go

The `logical.loop.runOnce()` method can enter a tight loop when it encounters an error condition, leading to logging spam. It uses a `timer.After` channel, which may already have fired by the time the `select` statement is executed when test code has set the RetryDelay value to a very small value.  (Also, golang says that the selection is arbitrary when multiple conditions are satisfied.)
This change enforces a minimum RetryDelay of 1 millisecond and adds an additional RetryDelay to `loop.runOnceUsing()`, again to prevent a tight delay from causing log spam in tests.
Existing uses of the 1 nanosecond value have been updated to show what their effective value will actually be.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

logical: Reduce test output spam

---

internal/sinktest/all/fixture.go
internal/source/cdc/config.go
internal/source/cdc/handler_test.go
internal/source/cdc/resolved_stamp.go
internal/source/cdc/resolver.go
internal/source/server/integration_test.go
internal/staging/stage/factory.go
internal/staging/stage/metrics.go
internal/staging/stage/queries/unstage.tmpl
internal/staging/stage/stage.go
internal/staging/stage/stage_test.go
internal/staging/stage/templates.go
internal/staging/stage/templates_test.go
internal/staging/stage/testdata/unstage.sql
internal/staging/stage/testdata/unstage_limit.sql
internal/staging/version/versions.go
internal/types/types.go
migrations/pr_572.md

This change moves tracking of partially-applied resolved timestamp windows into
the staging tables by adding a new `applied` column. The goal of this change is
to move some state-tracking out of the cdc resolver loop into the stage
package. Tracking apply status on a per-mutation basis improves idempotency of
cdc-sink when the userscript has non-idempotent behaviors (e.g.: three-way
merge). It also allows us to export monitoring data around mutations which may
have slipped through the cracks or to detect when a migration process has
completely drained. Fine-grained tracking will also be useful for unifying the
non-transactional modes into a single behavior.
Many unused methods in the stage API have been deleted. The "unstaging" SQL
query is now generated with a golang template and is …

stage: Track applied mutations in staging tables

---

internal/source/cdc/metrics.go
internal/source/cdc/resolver.go

We have been monitoring the progress of a CDC feed via the metrics exported from the logical package, but that doesn't have visibility into the state of the CDC resolver. For instance the `logical_commit_latency_seconds` metric can only tell an observer about the latest timestamp that was committed and not about the one being processed. There are also some performance counters that will help to identify where, in the logical+cdc stack, time is being spent.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/579)

cdc: Add metrics to resolver

---

.github/workflows/go-tests.yaml
internal/source/cdc/handler_test.go
internal/source/server/integration_test.go
internal/target/apply/apply_test.go
internal/target/schemawatch/coldata_test.go

This change uses an 8-core machine with more memory for running the unit tests. Several tests which were not marked as `t.Parallel()` due to resource constraints are allowed to run in parallel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/580)

workflows: Use larger machine shape for test suite

---

internal/source/pglogical/conn.go
internal/source/pglogical/integration_test.go

This change adds a test for an enum type in the source and target databases. When a UDT is used, a TypeMessage will be sent over the pglogical feed. We can ignore this message, since we interpret incoming data via the target typesystem.
Fixes #578
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/582)

pglogical: Add fix and test for UDT enum types

---

go.mod
internal/source/pglogical/config.go
internal/source/pglogical/conn.go
internal/source/pglogical/integration_test.go
internal/source/pglogical/metrics.go
internal/source/pglogical/provider.go

In Postgres older releases (<v15) the walsender sends an empty transaction if all DMLs in the transaction are not published to publication filter.
See https://github.com/postgres/postgres/commit/d5a9d86d8f. 
This change allows cdc-sink to skip these transactions without updating the last consistent point in the memo table. The change is gated behind the --skipEmptyTransactions configuration flag.
Adding two prometheus counters to track empty transactions and skipped empty transactions.
Fixes #588
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/589)

pglogical: skip empty transactions

---

internal/source/pglogical/config.go
internal/source/pglogical/conn.go
internal/source/pglogical/integration_test.go
internal/source/pglogical/metrics.go
internal/source/pglogical/provider.go
internal/target/apply/apply.go
internal/target/apply/queries/crdb/common.tmpl
internal/target/apply/queries/crdb/toasted.tmpl
internal/target/apply/templates.go
internal/target/apply/templates_test.go
internal/target/apply/testdata/crdb/base.toasted.sql
internal/types/types.go

This change allows source dialect to request custom upsert templates for specific mutations. The logical apply loop will use the custom template if available.
For instance, this is used to handle Postgres unchanged toasted columns. If a custom colum is detected, then a custom upsert template is used to query the current value of the toasted column in target database before inserting the mutation.
This change also adds a new configuration flag '--enableToastedColumns' which allows cdc-sink to support toasted columns when using Postres as a source.
Support is limited for logical replication with basic upserts into CRDB targets via a custom template (no user scripts or merge functionality).
When the experimental support for toasted columns is enabled, and cdc-sink receives a …

support for a mutation specific custom upsert template.

---

internal/source/pglogical/config.go
internal/source/pglogical/conn.go
internal/source/pglogical/integration_test.go
internal/source/pglogical/metrics.go
internal/source/pglogical/provider.go

Removed the --skipEmptyTransactions flag.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/609)

pglogical: enabling skipping empty transactions by default.

---

internal/source/pglogical/conn.go
internal/source/pglogical/integration_test.go
internal/source/pglogical/provider.go

Previously pglogical used a hardcoded value to determine how often to update the replication status back to the source.
This change allows the user to configure the frequency via the existing standbyTimeout command line parameter.
In addition the parameter determines how ofter to commit the consistent point in the memo table.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/608)

pglogical: using the parameter standbyTimeout to configure consistent point commit frequency.

---

internal/target/schemawatch/coldata_test.go
internal/target/schemawatch/dependencies.go

The queries used to compute table dependency order does not exclude views. This
change updates the queries and adds a test.
X-Ref: #617
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/618)

schemawatch: Exclude views from SchemaData.Order

---

go.mod
go.sum
internal/target/schemawatch/parse_helpers.go
internal/target/schemawatch/parse_helpers_test.go

The newest version of go-ora supports time.Time directly, removing the need for the custom wrapper types.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/624)

schemawatch: Remove deprecated go-ora time types

---

internal/script/applier.go
internal/script/injector.go
internal/script/loader.go
internal/script/provider.go
internal/script/script.go
internal/script/script_test.go
internal/script/testdata/cdc-sink@v1.d.ts
internal/script/testdata/main.ts
internal/script/testdata/tsconfig.json
internal/script/wire_gen.go
internal/source/fslogical/wire_gen.go
internal/target/apply/apply_test.go
internal/target/apply/factory.go
internal/target/apply/provider.go
internal/util/applycfg/conf.go
internal/util/applycfg/conf_test.go

This change allows the userscript to replace the default upsert and delete
behaviors in the apply package by supplying JS functions via
`api.configureTable()`. These functions are provided with a facade around a
target database transaction and the documents to be upserted or the primary
keys to be deleted.
Database access is asynchronous from the perspective of the userscript. The
database API is modeled using Promises, which allows us to release the
exclusive lock on the JS runtime while the database commands are executed in
another goroutine.  Results of database queries are provided using the
iteration protocal that allows the `for..of` syntax and which can respond to a
`break` statement by releasing the underlying database resources. The
background databases accesses are performed …

script: Allow userscript to execute SQL

---

internal/source/cdc/resolver.go
internal/source/fslogical/fslogical.go
internal/source/fslogical/tombstones.go
internal/source/logical/chaos.go
internal/source/logical/dialect.go
internal/source/logical/fake_dialect.go
internal/source/logical/fan_events.go
internal/source/logical/generator_test.go
internal/source/logical/loop.go
internal/source/logical/serial_events.go
internal/source/mylogical/conn.go
internal/source/pglogical/conn.go

The need for this method can be obviated by passing a stopper.Context into the Dialect implementations. There is no net change in functionality, since logical.State.Stopping() just delegated to the stopper.Context in the logical loop.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/625)

logical: Remove logical.State.Stopping() method

---

internal/source/logical/config.go
internal/source/logical/provider.go

The existing targetDBConns flag was ignored and we didn't have a flag for staging. This change allows both to be set.
Fixes #645
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/647)

logical: Correctly wire up db pool sizes

---

internal/source/logical/config.go

Backfill mode had indirectly dependended on the use of SELECT FOR UPDATE to ensure that mutations for two keys could not be in flight at once. When we removed the use of SFU because the locks weren't reliable during range transfers, backfill mode no longer had any particular guarantees about execution order.
The work to unify the non-transaction modes per issue #504 will provide a suitable replacement for the intended behavior of backfill mode. It will provide the option of allowing non-overlapping transactions to be applied concurrently in order to improve throughput.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/651)

logical: Disable the backfillWindow flag

---

internal/source/cdc/request.go
internal/source/cdc/url_test.go

This change updates the path parsing code to ignore empty path elements in the changefeed URLs. This avoids a mis-parsing when a user creates a changefeed into `/some/schema/` instead of `/some/schema`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/653)

cdc: Ignore empty path elements in feed URLs

---

internal/source/fslogical/fslogical.go

This adds a test to turn a nil dereference into an error. This code is going to be affected by the work on #504, so a deeper investigation is unwarranted at this time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/654)

fslogical: Workaround for chaos test panic

---

internal/script/loader.go
internal/script/script.go
internal/script/script_test.go
internal/script/testdata/cdc-sink@v1.d.ts
internal/script/testdata/main.ts
internal/source/logical/logical_test.go
internal/source/logical/script_events.go

This change allows the userscript to provide a mapping function for the primary key in a deletion. This supports use cases where the target schema has a different PK structure than the source. It is also possible to elide all deletes to a table by having the deleteKey function return null.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/652)

script: Allow PKs used for deletion to be rewritten

---

internal/util/stopvar/stopvar.go
internal/util/stopvar/stopvar_test.go

This change adds utilities for common patterns involving a stopper.Context and a notify.Var.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/674)

stopvar: Combined stopper and notify utilities

---

internal/util/hlc/hlc.go
internal/util/hlc/hlc_test.go
internal/util/hlc/range.go

This change adds a "plus one" method to hlc.Time and a Range type that represents a half-open range of timestamps.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/675)

hlc: Add Range type and Time.Next method

---

internal/util/notify/var.go
internal/util/notify/var_test.go

This change adds a sentinel error value that is suppressed by notify.Var.Update(). This provides a clean way for a callback to decline to update the variable without the caller having to perform a sentinel check.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/677)

notify: Add ErrNoUpdate

---

internal/cmd/fslogical/fslogical.go
internal/cmd/mylogical/mylogical.go
internal/cmd/pglogical/pglogical.go
internal/cmd/start/start.go
internal/util/stdlogical/stdlogical.go
internal/util/stdlogical/stdlogical_test.go

This change solves some upcoming lifecycle and startup complexities by having the stdlogical package bind and preflight the configuration object used by a command.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/678)

stdlogical: Add Config interface

---

internal/util/lockset/lockset.go
internal/util/lockset/lockset_test.go

This change adds a utility for ensuring in-order access to potentially-overlapping sets of resources.  This will be used to implement the "shingle" mode as proposed in #516 wherein multiple target transactions with non-overlapping rows are applied concurrently.
The Set maintains a queue of waiters for each requested resource. When a waiter has reached the head of its respective queues, a callback function is executed in a new goroutine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/676)

lockset: Add utility for resource ordering

---

internal/source/cdc/ndjson.go
internal/source/cdc/webhook.go
internal/staging/stage/factory.go
internal/staging/stage/metrics.go
internal/staging/stage/queries/unstage.tmpl
internal/staging/stage/stage.go
internal/staging/stage/stage_test.go
internal/staging/stage/templates.go
internal/staging/stage/templates_test.go
internal/staging/stage/testdata/ignore_lease.sql
internal/staging/stage/testdata/lease.sql
internal/staging/stage/testdata/unstage_limit.sql
internal/types/types.go

This change adds a new API to the stage package that allows mutations to be staged only if an unapplied mutation already exists for a row. This change also allows leases to be taken out on individual rows, to support the best-effort sequencer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/680)

stage: Add support for conditional staging

---

internal/sequencer/bypass/bypass.go
internal/sequencer/bypass/bypass_test.go
internal/source/cdc/handler_test.go

This change makes the bypass sequencer set the table progress to the end of the resolving range. This ensures that the checkpoint manager will be able to clean up old resolved timestamps that have accumulated. We know that we won't see a resolved timestamp message from a changefeed unless all previous payloads have processed. Thus, the table progress exactly matches the changefeed's cursor.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/694)

bypass: Advance table progress

---

internal/sequencer/script/acceptor.go
internal/types/acceptors.go
internal/types/acceptors_test.go

Previously dispatch would fail if the user provided script removed mutations. This change adds defensive check to the orderedAdapter to allow empty batches to be accepted by an Acceptor.
It also adds a check in the script.doDispatch to avoid additional processing if the results of a dispatch is empty.
Fixes #700.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/701)

userscript: allow users to remove mutations in dispatch.

---

internal/staging/stage/stage.go

This adds an index over the `key` column to speed up the check for unapplied mutations.
h/t @drewdeally
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/702)

stage: Add index for StageIfExists method

---

internal/staging/checkpoint/checkpoint_test.go
internal/staging/checkpoint/group.go

This change allows multiple calls to `Advance()` with the same timestamp, as long as the duplicate value is still the maximum. It appears that CockroachDB changefeeds can re-emit duplicate resolved timestamps when catching up.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/703)

checkpoint: Accept duplicate checkpoint timestamps

---

internal/source/cdc/config.go
internal/source/cdc/handler.go
internal/source/cdc/handler_test.go

This change avoids using the HTTP request context and instead uses a context with a configurable timeout. This will help to insulate cdc-sink from HTTP requests that are abandonded by the client (or which have a network blip). It is likely the case that the client will re-deliver the payload, but cdc-sink is already prepared to deal with the at-least-once behavior of CDC changefeeds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/715)

cdc: Decouple from HTTP request context

---

internal/sequencer/besteffort/best_effort.go
internal/sequencer/besteffort/besteffort_test.go

The implementation of sweepOnce should have been embarrassingly parallel. Instead, it was embarrassingly serial, which limited catch-up throughput.
This change makes sweepOnce act similarly to the best-effort acceptor type, where each single-mutation batch is attempted in parallel.
An extra test focusing on the catch-up case is added. It can be used an an ersatz performance-tuning exercise by increasing the number of backfilled mutations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/708)

besteffort: Make sweepOnce parallel

---

internal/sequencer/script/acceptor.go
internal/sequencer/script/provider.go
internal/sequencer/script/script.go
internal/sequencer/script/script_test.go
internal/sequencer/seqtest/seqtest.go
internal/sequencer/seqtest/wire_gen.go
internal/sequencer/switcher/switcher.go
internal/source/cdc/server/wire_gen.go
internal/source/cdc/wire_gen.go
internal/source/mylogical/wire_gen.go
internal/source/pglogical/wire_gen.go

This change allows user-defined apply functions to work in immediate mode by having the script Sequencer shim create and commit a database transaction. The userscript sequencer test is expanded to cover all core sequencer modes to ensure broad compatibility.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/716)

script: Enable user-defined apply functions to work in immediate mode

---

internal/sequencer/script/script_test.go
internal/sequencer/serial/serial.go
internal/sequencer/serial/serial_test.go
internal/sequencer/shingle/shingle_test.go
internal/sequencer/switcher/switcher_test.go
internal/sinktest/all/fixture.go
internal/source/cdc/handler_test.go
internal/staging/stage/factory.go
internal/staging/stage/queries/unstage.tmpl
internal/staging/stage/stage_test.go
internal/staging/stage/testdata/ignore_lease.sql
internal/staging/stage/testdata/lease.sql
internal/staging/stage/testdata/unstage.sql
internal/staging/stage/testdata/unstage_limit.sql
internal/types/types.go

This change improves the performance of the unstage query when running against large amounts of staged data. Previously, we tried to identify the candidate timestamps to operate on and then the staged rows to update. In this new query, we identify candidate rows that might be updated by the query and then filter with the first N timestamps.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/714)

stage: Rework unstage query to improve performance

---

internal/sequencer/besteffort/best_effort.go
internal/sequencer/besteffort/besteffort_test.go
internal/sequencer/besteffort/metrics.go
internal/sequencer/besteffort/provider.go
internal/source/cdc/handler_test.go
internal/source/cdc/test_fixture.go
internal/source/cdc/wire_gen.go

This change allows the BestEffort sequencer report to partial progress while
it's working on checkpoint ranges of (potentially) unbounded size. This ensures
that checkpoint entries can be marked as applied during long-running catch-up
situations. Previously, the low-watermark would be updated only after an entire
scan had completed.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/709)

besteffort: Improve progress reporting in best-effort mode

---

internal/sequencer/serial/serial_test.go
internal/staging/checkpoint/checkpoint_test.go
internal/staging/checkpoint/group.go

This change updates the checkpoint API to emit smaller bounds ranges.  Rather than emitting the newest-applied to the newest-timestamp window, it chooses the next proposed timestamp after the newest applied timestamp. This ensure that the serial sequencer can report incremental progress and also reduces the maximum amount of data that could be operated on at once.
A test that was useful for performance tuning in the besteffort package has been copied into the serial package.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/719)

checkpoint: Reduce size of the resolving window

---

internal/sequencer/immediate/immediate.go
internal/sequencer/immediate/immediate_test.go
internal/sequencer/immediate/provider.go
internal/sequencer/seqtest/seqtest.go
internal/sequencer/seqtest/wire_gen.go
internal/sequencer/switcher/group.go
internal/sequencer/switcher/mode_string.go
internal/sequencer/switcher/provider.go
internal/sequencer/switcher/switcher.go
internal/source/cdc/server/wire_gen.go
internal/source/cdc/targets.go
internal/source/cdc/wire_gen.go
internal/source/mylogical/injector.go
internal/source/mylogical/provider.go
internal/source/mylogical/wire_gen.go
internal/source/pglogical/injector.go
internal/source/pglogical/provider.go
internal/source/pglogical/wire_gen.go

This change renames the bypass sequencer to immediate to be consistent with documentation. Other uses of the phrase "bypass" have also been renamed. There are no functional changes in this commit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/722)

Rename bypass sequencer to immediate

---

internal/script/bag_wrapper.go
internal/script/bag_wrapper_test.go
internal/script/safe_value.go
internal/script/safe_value_test.go
internal/script/script.go
internal/script/script_test.go
internal/script/target_tx.go
internal/script/testdata/main.ts
internal/target/apply/apply.go

This change corrects an inconsistency in how values loaded from the target database versus those from incoming changefeed values are presented to the userscript. Previously, types such as time.Time would be presented as a basic string when received from a changefeed, while the values loaded from the database were presented as a proxied time.Time. Large magnitude numbers were also impacted by JavaScript's 53-bit mantissa limitation.
All values presented to the userscript are passed through a utility function which ensures a consistent, JSON-like presentation of the value to the script.
The apply.IsMergeSupported() function is added to improve test readability.
Breaking change: Performing math using basic JavaScript numeric types should not be undertaken lightly, due to potential loss of …

script: Present database values as reified JSON values

---

internal/staging/stage/stage.go
internal/staging/stage/stage_test.go

The monitoring query to count the number of unapplied mutations should be moved to follower reads. Otherwise, it can create contention on the staging indexes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/729)

stage: Make unapplied metrics count AOST

---

internal/script/loader.go
internal/script/provider.go
internal/script/script.go
internal/script/script_test.go
internal/sequencer/seqtest/wire_gen.go
internal/source/cdc/server/wire_gen.go
internal/source/cdc/wire_gen.go
internal/source/mylogical/wire_gen.go
internal/source/pglogical/wire_gen.go
internal/util/stdlogical/stdlogical.go
internal/util/workgroup/workgroup.go
internal/util/workgroup/workgroup_test.go

The userscript limits the number of concurrently-executing promise goroutines
to prevent accidental resource exhaustion. The current implementation uses an
`errgroup.Group` with a limit. However, this can create a deadlock situation
where `execTrackedPromise` blocks on the call to `Go()`. Since promises are
being constructed while already in `execTrackedJS()`, we can wind up with a
deadlock situation where other promise resolutions are waiting to enter the
userscript mutex.
This change adds a simple workerpool implementation which provides an upper
bound on the number of worker goroutines and the maximum number of pending
tasks.
The stdlogical package, which installs the global pprof handlers, now also
sets a reasonable default for block and mutex profiling.
Fixes #730
- - -
This change …

script: Use a queuing, not blocking, Promise concurrency limit

---

internal/source/cdc/server/injector_test.go
internal/source/cdc/server/provider.go
internal/source/cdc/server/wire_gen.go
internal/source/mylogical/provider.go
internal/source/mylogical/wire_gen.go
internal/source/pglogical/provider.go
internal/source/pglogical/wire_gen.go
internal/util/stdlogical/stdlogical.go

This change moves configuration preflighting out of stdlogical and into the Wire injector. This restores the previous behavior of allowing the userscript to drive all CLI options (e.g. `--targetConn`).
Fixes #733
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/738)

source: Defer configuration preflight until script has loaded

---

internal/script/loader.go
internal/script/safe_value.go
internal/script/safe_value_test.go
internal/script/script.go
internal/script/script_test.go
internal/source/cdc/handler_test.go
internal/util/crep/crep.go
internal/util/crep/crep_test.go
internal/util/crep/equal.go
internal/util/crep/equal_test.go
internal/util/merge/standard.go
internal/util/merge/standard_test.go

This PR contains three commits. The first extracts the value-canonicalization code from the script package into a new package. The second expands upon the first by adding an equality comparison and updating the standard merge function. The third commit is the test that was written first to prove out the other commits.
See #732 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/735)

Correctly merge time.Time or other complex types

---

.github/docker-compose.yml
.github/workflows/go-tests.yaml

This promotes v23.2 to be the primary version tested. A v23.1-only test is added to ensure ongoing compatibility.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/739)

workflow: Test CockroachDB v23.2

---

internal/script/config.go
internal/script/provider.go
internal/script/script_test.go

This is a follow-up from #738. The call to `script.Config.Preflight` is necessary to populate the FS field. The script test no longer uses an embedded FS so that this code may be exercised.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/746)

script: Ensure script.Config.Preflight is called.

---

internal/sinktest/base/provider.go
internal/util/stdpool/size.go

This commit undoes the change to the maximum idle connection count for the
sql.DB pool from PR https://github.com/cockroachdb/cdc-sink/pull/740. Having a low setting caused an excessive amount of
connection pool thrash at high parallelism settings. We do keep the pgx
MinConns setting so we, generally, open connections on demand and then allow
them to age out.
The testing pools are configured with an explicit idle lifetime. We see issues
with go-ora where allowing idle connections to remain open, seems to cause all
connections in the pool to be canceled at once. This setting is also consistent
with the production pool setup code.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc- …

stdpool: Restore sql.DB maximum idle connection count

---

internal/sequencer/besteffort/acceptor.go
internal/sequencer/besteffort/best_effort.go
internal/sequencer/sequtil/deferrable.go
internal/sequencer/shingle/acceptor.go
internal/util/lockset/lockset.go
internal/util/lockset/lockset_test.go

This PR consists of two commits which enable `lockset.Set` to retry tasks when they have
reached the head of a global queue and for the `shingle` sequencer to make use of this functionality.
This changes the shingle acceptor to automatically retry FK constraint
violations or other deferrable errors if there were potentially-blocking
segments already in flight. Previously, these FK errors would cause the entire
shingled batch to be retried after the quiescent period elapsed, leading to
throughput hiccups. The existing sequencer test suite already exercised the
top-level FK-ordering retry behavior.
The is-deferrable-error function has been moved out of the besteffort package
into the sequtil package.
Fixes #748
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

shingle: Add fast retry path for FK constraint violations

---

internal/sequencer/besteffort/best_effort.go
internal/sequencer/immediate/immediate.go
internal/sequencer/serial/serial.go
internal/sequencer/switcher/switcher_test.go
internal/util/applycfg/configs.go
internal/util/notify/var.go
internal/util/notify/var_test.go

This change adds a convenience function for creating a notify.Var set to an initial value. Unnecessary calls to notify.Var.Set have been updated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/773)

notify: Add VarOf convenience constructor

---

internal/sequencer/scheduler/scheduler.go
internal/sequencer/seqtest/fragment.go
internal/types/batches.go
internal/types/batches_test.go

This change adds a general-pupose, ordered, traversal mechanism to the batch types. This supports an upcoming commit and a few existing batch traversals are update to use CopyInto.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/775)

types: Add CopyInto methods to mutation batch types

---

internal/util/lockset/lockset.go
internal/util/lockset/lockset_test.go

This PR is stacked on #773 
This change allows the request for a retry to be accompanied by an optional
callback to be invoked if the request will not be honored. That is, the callback
will be invoked if the task was already at the head of the global queue.
Testing this revealed a state-transition bug that could happen if a task was
moved to the head of the queue while is was already executing. The retry
request would be rejected since the task would be at the end of the queue when
its callback finished. If the task did not start at the head of the global
queue, it will re-enqueue itself.
Some additional API conveniences are added, to be used in a subsequent commit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

lockset: Add callback to RetryAtHead

---

.github/workflows/go-tests.yaml

This change sets the `continue-on-error` flag on the job step that uploads code coverage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/786)

workflow: Make CodeCov upload optional

---

.github/docker-compose.yml
.github/workflows/go-tests.yaml
go.mod
go.sum
internal/source/cdc/server/integration_test.go

This change updates the build matrix to require cdc-sink to be able to use the
CockroachDB versions that are within the maintenance window as staging and
target databases. Older versions of CockroachDB are tested only as changefeed
sources.
The server integration test is cleaned up a bit to use the semver comparison
function from the go mod tool.
Support for v20.1 as a source is re-enabled.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/781)

workflow: Revise matrix testing

---

internal/target/apply/apply.go

The existing code reports a meaningless value if the call to Parse fails. The assignment to the value variable is deferred until after the error check.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/784)

apply: Report original value if ColData.Parse fails

---

internal/staging/stage/metrics.go
internal/staging/stage/stage.go

This change adds a new metric to count the number of duplicate mutations that have been received. The staging query is changed from an `UPSERT` to an `IOCDN` since the upsert always returns the number of rows in its input, regardless of whether any change took place.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/791)

stage: Add metric to track number of duplicate mutations

---

internal/source/cdc/config.go
internal/source/cdc/handler.go

This adds an additional flag to the CDC configuration to add an arbitrary amount of delay when discarding input.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/800)

cdc: Add configurable discard delay

---

internal/sequencer/script/acceptor.go

This updates the doMap method to exit early if no target is configured.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/803)

sequencer/script: Fix possible nil dereference

---

internal/script/metrics.go
internal/script/script.go

This change adds two histograms showing the time spent waiting to enter the VM and the time spent executing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/802)

script: Add metrics showing time in the userscript VM

---

scripts/dashboard/cdc-sink.json

This change fixes the grafana replicator dashboard ad-hoc filtering by using the DS_PROMETHEUS variable in place of the hardcoded uid.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/808)

dashboard: removing hardcoded datasource uid from filters.

---

internal/source/cdc/metrics.go
internal/source/cdc/targets.go

This change adds a top-level counter to show the number of incoming mutations received and further classifies them based on success or failure. This can be used to determine the number of mutations that may be filtered out due to data behaviors or other configurations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/810)

cdc: Add a top-of-funnel mutations counter

---

internal/target/apply/apply.go
internal/target/apply/metrics.go
scripts/dashboard/cdc-sink.json

This change adds a histogram that tracks the age of the data being applied to a table. An updated dashboard has been exported to graph the P99 value.
Fixes #809
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/811)

apply: Add mutation age histogram

---

internal/util/stdpool/crdb_hints.go
internal/util/stdpool/crdb_hints_test.go

The regex used in crdb_hints.go did not consider prerelease versions. The pattern has been extended to consume the extra prerelease values.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/818)

stdpool: Extract prerelease version strings correctly

---

internal/sequencer/scheduler/provider.go
internal/sequencer/scheduler/scheduler.go
internal/sequencer/scheduler/scheduler_test.go
internal/util/lockset/lockset.go
internal/util/lockset/lockset_test.go
internal/util/lockset/metrics.go
internal/util/retry/retry.go
scripts/dashboard/cdc-sink.json

This change adds metrics to the lockset.Set type to track wait times and the number of tasks that could be started immediately, were deferred, or were retried. A constructor function is added to initialize the metrics using a mandatory Runner instance and metrics label.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/822)

lockset: Add metrics

---

.github/workflows/go-docker.yaml

Docker image pushes are not additive. This builds and pushes the AMD and Arm builds in a single stage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/826)

workflows: Fix docker push setup

---

internal/script/loader.go
internal/script/script.go
internal/script/script_test.go
internal/script/testdata/cdc-sink@v1.d.ts
internal/script/testdata/main.ts
internal/target/apply/apply.go
internal/target/apply/column_mapping.go
internal/util/applycfg/conf.go
internal/util/applycfg/conf_test.go

The pgwire protocol has a limit of 2^15 bind variables per statement. The number of bind variables in our generated SQL is rows*colums, which means that extremely wide tables can run into a practical limit on the number of rows that can be sent in a single statement. Our current default number of rows is 100, which is somewhat conservative for normal-width schemas.
This change adds a new field to apply.Config that controls the number of rows to send for non-bulk targets. It is exposed via the userscript and adjusts the capacity of the buffers used when assembling database payloads.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/831)

apply: Add knob for per-statement row limit

---

.github/workflows/go-binaries.yaml

The glibc runtime dependency is set by the version of the toolchain used to compile the binary. This rolls the builder image back to Ubuntu 20.04 to use an older glibc version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/832)

workflow: Build Oracle Database target on old glibc

---

internal/source/cdc/metrics.go
internal/source/cdc/targets.go
internal/types/counter.go
internal/types/counter_test.go

Currently, the cdc source package uses a counting acceptor wrapper to record all the mutations that are pushed through the acceptor machinery, and exposes metrics to track outcomes.
This change moves the counting acceptor and relative metrics to the types package, so it can be reused by other sources.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/833)

acceptor: Moving CountingAcceptor to types, so it can be reused.

---

Dockerfile

The committed file is missing a `-tags` setting to actually enable the Oracle Database target. A smaller set of package dependencies for the base image has been identified.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/834)

Dockerfile: Fix copy-pasto in RUN line

---

internal/util/stdpool/ora.go

This change ensures that the connections to Oracle Database are UTC-clean, unless otherwise configured by the end user. It prevents timestamp offsets from being applied if the local system timezone is not UTC.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/835)

stdpool: Set Oracle connections to UTC timezone

---

internal/sequencer/config.go

The default for the flush period is too aggressive, leading to excessively small target transaction sizes. In general, we expect that the flushSize flag should drive the size of the target transactions. Changing the flush period to one second ensures that target transactions should fill to the target size.
The flush period setting can't be eliminated entirely, however. In high-rate situations where the flush size is very large, the read cursor might take an arbitrarily long time to catch up to the write cursor which would prevent partial progress from being made.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/840)

sequencer: Adjust default flush period

---

internal/source/cdc/resolved.go
internal/source/cdc/targets.go
internal/staging/checkpoint/checkpoint.go
internal/staging/checkpoint/checkpoint_test.go
internal/staging/checkpoint/group.go
internal/staging/checkpoint/migrate.go
internal/staging/checkpoint/migrate_test.go
internal/staging/checkpoint/provider.go
internal/staging/version/versions.go
internal/util/hlc/hlc.go
internal/util/hlc/hlc_test.go
migrations/pr_828.md

This change supports checkpoints that are aggregated across multiple
partitions. A checkpoint will advance only when all of its constituent
partitions have advanced to some common minimum value.
The hlc.Time type now implements the sql.Scanner and sql.driver.Valuer
interfaces to allow it be used directly with the sql API.
Breaking change: This commit includes an automated schema migration that
requires manual coordination if multiple instances of cdc-sink are used.
* Stop all instances of cdc-sink
* Mark the migration as complete:
```sql
UPSERT INTO _cdc_sink.memo (key, value) VALUES ('version-828','{"state":"applied"}');
```
* Start a single instance of cdc-sink and wait for the automatic migration to occur.
* Start any remaining instances as necessary.
- - -
This change is [<img …

checkpoint: Support for partitioned checkpoints

---

internal/source/kafka/config.go
internal/source/kafka/config_test.go
internal/source/kafka/conn.go
internal/source/kafka/conn_test.go
internal/source/kafka/consumer.go
internal/source/kafka/integration_test.go
internal/source/kafka/metrics.go
internal/source/kafka/mocks/client.go
internal/source/kafka/mocks/consumer.go
internal/source/kafka/mocks/partition.go
internal/source/kafka/offset.go
internal/source/kafka/offset_test.go
internal/source/kafka/payload.go
internal/source/kafka/payload_test.go

This change improves the logic to find an adequate offset to start the event replay. We return the offset of the most recent resolved timestamp message that is stricly less than the minimum timestamp provided by the user.
A new set of metrics have been added to track the total number of messages that have been replayed, and the number of messages read to find the resolved timestamp.
A new mock client and consumer have been introduced to facilitate testing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/824)

kafka: finding proper offset to start replay, given a min timestamp

---

.github/ISSUE_TEMPLATE/bug_report.md
internal/script/applier.go
internal/script/help_command.go
internal/script/loader.go
internal/script/provider.go
internal/script/script.go
internal/script/script_test.go
internal/script/testdata/legacy_import.ts
internal/script/testdata/main.ts
internal/script/testdata/replicator@v1.d.ts
internal/script/testdata/tsconfig.json
internal/sequencer/script/script_test.go
internal/source/cdc/server/injector_test.go
scripts/active_active/README.md
scripts/active_active/userscripts/cdc-sink@v1.d.ts
scripts/active_active/userscripts/repl.ts
scripts/active_active/userscripts/replicator@v1.d.ts
scripts/active_active/userscripts/tsconfig.json

This change replaces the use of `cdc-sink@v1` with `replicator@v1`. Compatibility with existing scripts is retained by allowing the same API object to be imported using the old name. A test is added for this legacy case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/849)

userscript: Move to new JS module name

---

internal/cmd/dumptemplates/dumptemplates.go
internal/target/apply/queries/crdb/common.tmpl
internal/target/apply/queries/crdb/conditional.tmpl
internal/target/apply/queries/crdb/delete.tmpl
internal/target/apply/queries/crdb/toasted.tmpl
internal/target/apply/queries/crdb/upsert.tmpl
internal/target/apply/queries/my/common.tmpl
internal/target/apply/queries/my/conditional.tmpl
internal/target/apply/queries/my/delete.tmpl
internal/target/apply/queries/my/upsert.tmpl
internal/target/apply/queries/ora/common.tmpl
internal/target/apply/queries/ora/delete.tmpl
internal/target/apply/queries/ora/upsert.tmpl
internal/target/apply/queries/pg/common.tmpl
internal/target/apply/queries/pg/conditional.tmpl
internal/target/apply/queries/pg/delete.tmpl
internal/target/apply/queries/pg/upsert.tmpl
internal/target/apply/templates.go
internal/target/apply/testdata/my/base.upsert.sql
internal/target/apply/testdata/my/cas.upsert.sql
internal/target/apply/testdata/my/casDeadline.upsert.sql
internal/target/apply/testdata/my/deadline.upsert.sql
internal/target/apply/testdata/my/expr.upsert.sql
internal/target/apply/testdata/my/ignore.upsert.sql
internal/target/apply/testdata/my/source names.upsert.sql

The env variable is now `REPLICATOR_TEMPLATES` instead of `CDC_SINK_TEMPLATES`. I doubt that this is commonly used at this point, but if you think it's necessary, I can add a check for the legacy value and just throw an error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/853)

Updating the templates, dump and the env variable to be Replicator

---

.github/workflows/go-binaries.yaml
.github/workflows/go.yaml
.github/workflows/package.sh
.gitignore

This change migrates to the new replicator.cockroachdb.com storage bucket.
Tarballs are pushed to an `edge/sha/` path prefix on every build. Branch builds
are pushed to an `edge/branch/` path. Version tags will be pushed to the top
level of the bucket. As before, links to the uploaded file(s) will be reported
as a workflow status message.
The bulk of the shell code is pulled out into a separate file so that it may be
run locally for testing.
h/t to @rail for Workload Identity Federation setup
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/855)

workflows: Refresh binary distributions

---

.github/workflows/go-binaries.yaml

The output from the uploads step is a comma-separated list. This splits the value to produce multiple links when appropriate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/857)

workflow: Fix upload links when multiple tarballs are created

---

.github/workflows/go-docker.yaml
.github/workflows/go.yaml

This change updates the destination DockerHub container name. It also enables
pushing edge builds to ghcr.io and pruning them.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/860)

workflows: Refresh Docker Builds

---

internal/staging/leases/leases.go
internal/staging/leases/leases_test.go

The tests in this package need to adjust timeouts and polling intervals. The existing tests are subject to a race condition during cleanup. This change creates a shallow copy before adjusting the configuration, so no deferred restoration is necessary.
Fixes #867
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/868)

leases: Fix race condition in test code

---

internal/source/mylogical/conn.go
internal/source/mylogical/conn_test.go

This change fixes a panic that could be caused by rows in a stream not conforming to the schema provided in TableMapEvents.
It also adds test cases to verify the functionality of onDataTuple function.
Fixes #858.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/875)

mysql: fixing index out of bounds in conn.go

---

internal/target/schemawatch/parse_helpers.go
internal/target/schemawatch/parse_helpers_test.go

If a UUID is stored in the source as a BYTEA type, it will appear within a changefeed as a hex-encoded string with a two-byte prefix. This change looks for this pattern and makes the value decodable by our UUID library by stripping the prefix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/880)

schemawatch: Add hex-escaped UUID parse helper for Oracle

---

internal/util/notify/var.go
internal/util/notify/var_test.go

This change adds a more straightforward way of swapping the current value of a notify.Var without having to call the Update method.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/882)

notify: Add Var.Swap method

---

internal/util/lockset/lockset.go
internal/util/lockset/lockset_test.go
internal/util/lockset/queue.go
internal/util/lockset/queue_test.go

This change splits the logic within lockset.Set into a separate lockset.Queue type, which can be used to solve for dependency orderings across asynchronous tasks on the fly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/881)

lockset: Extract a Queue type

---

.github/docker-compose.yml
.github/workflows/go-tests.yaml

This change runs tests against the cockroach-unstable image, with the caveat that the job may fail without breaking the build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/884)

workflow: Add cockroach-unstable to test matrix

---

.github/workflows/go-tests.yaml

This fixes a dangling reference to the old storage bucket.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/890)

workflows: Update location of OIC library cache

---

.github/workflows/dependabot.yaml

The auto-merge recipe now requires the use of a Personal Access Token; the use of GITHUB_TOKEN won't allow the dependent workflows in the merge queue to actually get kicked off. Consequently, the PR is added to merge queue, but the tests never run. This change removes the auto-merge setup, since it's not particularly taxing to click the green button.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/891)

workflows: Remove dependabot automerge

---

internal/source/mylogical/conn.go
internal/source/mylogical/conn_test.go
internal/source/mylogical/integration_test.go

Previously, running replicator for my logical with a target database name that was different from the source database name would fail.
This change allows target database name to be different for mylogical, similarly to the pglogical behavior.
Integration tests have been updated to verify the change.
Fixes #894.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/895)

mysql: allowing target database name to be different from source database name.

---

.github/release.yml
.github/workflows/go-binaries.yaml
.github/workflows/go.yaml

This change adds an automatic release notes configuration. PRs are categorized by `R-*` labels to populate the initial release notes.
The go build workflow will now trigger on a GitHub release being created, instead of on pushing a version tag. This will allow tarballs to be attached to the Release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/896)

workflows: Initial release workflow

---

internal/source/cdc/handler.go
internal/source/cdc/handler_test.go
internal/source/cdc/ndjson.go
internal/source/cdc/primary_key.go
internal/source/cdc/provider.go
internal/source/cdc/request.go
internal/source/cdc/url_test.go
internal/source/cdc/webhook_query.go
internal/util/cdcjson/ndjson_parser.go
internal/util/cdcjson/ndjson_parser_test.go
internal/util/cdcjson/query_payload.go
internal/util/cdcjson/query_payload_test.go
internal/util/cdcjson/reader.go
internal/util/cdcjson/reader_test.go

The functionality within the cdc that is used to process json can be reused by other source (namely, cloud storage connectors).
This change moves such functionality under the util packages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/900)

ndjson: moving ndjson parser to the util package so they can be reused.

---

internal/cmd/workload/workload_test.go
internal/sequencer/besteffort/besteffort_test.go
internal/sequencer/core/core_test.go
internal/sequencer/immediate/immediate_test.go
internal/sequencer/seqtest/check.go
internal/sequencer/switcher/switcher_test.go
internal/sinktest/all/workload.go
internal/source/cdc/handler_test.go

This change adds some extra configuration plumbing so that the Immedate sequencer can be tested and verified with approximately the same tests used on other sequencers. The points of configuration are to disable foreign keys in the target schema and to skip any tests which would pre-populate staging tables.
X-Ref: #898
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/901)

seqtest: Make CheckSequencer work with Immediate

---

internal/source/objstore/bucket/errors.go
internal/source/objstore/providers/local/local.go
internal/source/objstore/providers/local/local_test.go
internal/source/objstore/providers/s3/s3.go
internal/source/objstore/providers/s3/s3_test.go
internal/source/objstore/providers/storetest/suite.go

This change adds a ErrTransient error that providers may use to identify transient errors to signal to clients that operation may be retried.
This change also adds a ErrSkipAll error that client may use in the Walk function to indicate that all remaining entries should be skipped.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/903)

objstore: adding ErrTransient and ErrSkipAll error markers.

---

internal/staging/memo/memory.go
internal/staging/memo/memory_test.go

This change adds a in-memory implementation of types.Memo that can be used for testing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/913)

memo: adding in-memory implementation.

---

go.mod

This change updates the minimum go version to pick up some security-related fixes in the http and net packages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/918)

go.mod: Update go to 1.22.4

---

internal/source/objstore/providers/s3/s3.go

This change fixes a go routines leak in the S3 provider. When calling ListObjects in the bucket.Walk we have to drain the receiving channel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/922)

objstore: fixing go routines leak.

---

internal/script/loader.go
internal/script/script.go
internal/script/script_test.go
internal/script/testdata/main.ts
internal/script/testdata/replicator@v1.d.ts
internal/sequencer/script/acceptor.go
internal/sequencer/script/script_test.go
internal/sinktest/scripttest/testdata/logical_test.ts

This change adds an optional user callback to configureSource() that is like the dispatch function, but for deletes. It receives the keys of the records to delete and returns a mapping of tables to primary keys.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/925)

script: Allow custom routing of deletions

---

internal/sequencer/script/acceptor.go
internal/sequencer/script/script_test.go

The metata for a mutation was not being added to deletes passing through the script acceptor. This moves the computation up in the for loop and adds a test to validate the script acceptor wiring.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/930)

sequencer/script: Ensure meta info is added to delete mutations

---

.github/workflows/go-tests.yaml
scripts/dashboard/README.md
scripts/docker_c2c/run_compose.sh

The docker-compose command has become deprecated on the GitHub runners in favor of a "docker compose" subcommand. This change also updates some passing references to the command to reflect current usage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/949)

workflows: Replace docker-compose with docker compose

---

internal/sinktest/base/log_config.go
internal/source/pglogical/integration_test.go
internal/util/logfmt/logfmt.go
internal/util/logfmt/metrics.go
main.go
scripts/dashboard/replicator.json

This change adds a metrics counter to identify spikes in workload error rates. The dashboard is updated to graph errors and warnings.
Errors that are often a side-effect of some other malfunction are labeled with a "noisy" property to allow them to be filtered when log-mining.
Log messages will now include the source of the logging call when trace mode is enabled.
A default logging configuration is installed by the sinktest/base package.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/944)

logfmt: Improve log output ergonomics

---

internal/target/apply/apply.go
internal/target/schemawatch/watcher.go
internal/target/schemawatch/watcher_test.go
internal/types/acceptors_test.go
internal/types/types.go

This change updates the Watcher.Watch() method to return a notify.Var to make it consistent with other sources of asynchronous updates. This will make a follow-on change to cache the target's schema cleaner to implement.
X-Ref: #902
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/952)

schemawatch: Refresh Watch method to return a notify.Var

---

internal/sequencer/seqtest/check.go
internal/source/cdc/handler_test.go
internal/staging/stage/consistency.go
internal/staging/stage/consistency_test.go
internal/staging/stage/metrics.go
internal/staging/stage/stage.go
internal/types/types.go

This change adds a sanity check to the staging package to ensure that the staging table entries are marked as applied in an order which is consistent with the order in which the entries are staged. This check is optionally enabled in Stager.MarkApplied() by an environment variable. The check is also used to drive a monitoring metric.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/957)

stage: Add optional staging table consistency checks

---

internal/staging/stage/table_merger_test.go
internal/staging/stage/table_reader.go
internal/staging/stage/table_reader_test.go
internal/types/types.go

It is possible for a reader to re-emit rows in subsequent cursors if it has reached an idle state and the bounds variable is updated without advancing the minimum value. This will happen if a slow target database delays the resolved timestamp bound from advancing before a new resolved timestamp is accepted for processing.
This change updates the behavior of the table reader such that it will not re-emit rows, regardless of how the bounds variable is driven.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/959)

stage: Prevent table reader from jumping backwards

---

internal/types/acceptors.go
internal/types/acceptors_test.go

This change adds a sanity check for tables that have no defined apply order. This prevents a case where, depending on how the acceptor chain is constructed, mutations for unknown tables could be silently ignored.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/970)

types: Add check to OrderedAcceptor for unknown tables

---

internal/sequencer/script/acceptor.go
internal/sequencer/script/script.go
internal/types/acceptors.go
internal/types/acceptors_test.go

The userscript doesn't actually need to iterate over incoming batches in any particular order. This change replaces the use of OrderedAcceptorFrom() with a new UnorderedAcceptorFrom() that merely adapts the TableAcceptor type to a MultiAcceptor. This will allow the script to better interface with as-yet-unknown tables when addressing partitioned, fan-in use cases.
An outdated doc comment on OrderedAcceptorFrom() is corrected.
See also #970
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/971)

sequencer/script: Remove unnecessary table ordering

---

internal/source/objstore/bucket/bucket.go
internal/source/objstore/config.go
internal/source/objstore/integration_test.go

This change adds an integration test suite that leverages the workload.Checker. The workload produces ndjson files and resolved timestamps and stores them in a bucket. The objstore connector process the files and inserts them into a target database, testing immediate and consistent mode.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/943)

objstore: adding integration test using workload.Checker.

---

go.mod
go.sum
internal/sequencer/besteffort/best_effort.go
internal/sequencer/config.go
internal/sequencer/core/core.go
internal/sequencer/core/round.go
internal/sequencer/sequtil/lease_group.go

This change corrects a context-break, where callbacks executed by the key scheduler were executed using a context from the scheduler's workgroup. In cases where the lease loop recycles and the target database is executing slowly, the old queries were not guaranteed to have been canceled when the next iteration of the loop starts.
This commit depends on https://github.com/cockroachdb/field-eng-powertools/pull/4
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/981)

sequencer: Improve visibility of long-running background tasks

---

internal/conveyor/config.go
internal/conveyor/conveyor.go
internal/staging/checkpoint/checkpoint.go
internal/staging/checkpoint/checkpoint_test.go
internal/staging/checkpoint/group.go
internal/staging/checkpoint/migrate_test.go
internal/staging/checkpoint/options.go

Currently, the checkpointing code always returns the latest checkpoint when computing the resolving range. This maximizes the number of mutations that can be concurrently applied, but it also means that if an apply transaction is delayed, say by encountering a locked row in the target database, the amount of temporal skew in the target data is also unbounded.
This change allows the operator to limit the number of checkpoints that will be considered when computing the upper bound of the resolving range. Lowering this value may have an adverse impact on total throughput.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/983)

checkpoint: Add option to limit the resolving range

---

internal/sinktest/all/wire_gen.go
internal/source/cdc/server/test_fixture.go
internal/source/cdc/server/wire_gen.go
internal/source/cdc/test_fixture.go
internal/source/cdc/wire_gen.go
internal/source/kafka/wire_gen.go
internal/source/mylogical/wire_gen.go
internal/source/objstore/wire_gen.go
internal/source/pglogical/wire_gen.go
internal/staging/memo/memory.go
internal/target/schemawatch/backup.go
internal/target/schemawatch/backup_test.go
internal/target/schemawatch/factory.go
internal/target/schemawatch/provider.go
internal/target/schemawatch/watcher.go

Store the schema to the staging memo, and restore it when the target database is down on startup.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/980)

Add a schema backup/restore mechanism

---

internal/staging/checkpoint/checkpoint.go
internal/staging/checkpoint/checkpoint_test.go
internal/staging/checkpoint/group.go

The previous iteration of this query did not correctly handle operating on an existing checkpoint table. The applied limit would prevent the query from scanning ahead to actually find new work to do. This change reworks the query to progressively narrow the range of timestamps for each checkpoint partition before applying the limit. The test is also updated to ensure that the restart case is correctly handled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/985)

checkpoint: Rework limited checkpoint scan query

---

internal/sequencer/chaos/chaos.go
internal/sequencer/config.go
internal/sequencer/seqtest/check.go
internal/source/kafka/integration_test.go
internal/source/mylogical/integration_test.go
internal/source/objstore/integration_test.go
internal/source/pglogical/integration_test.go

The chaos shim currently returns ErrChaos based on a probability. It has proven difficult to choose probabilities that are guaranteed to test all error-return paths but that don't slow testing arbitrarily. This change makes the chaos acceptor return an error a defined number of times per unique stack trace.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/989)

chaos: Cover each distinct stack trace

---

internal/sinktest/base/provider.go
internal/util/stdpool/ora.go
internal/util/stdpool/ora_unsupported.go

This change updates how the Oracle Database connection pool is set up. Rather than running tests while connected as the SYSTEM user, we'll reconnect as the role we've already created for the fixture's tables. This will help identify explicit grants that a Replicator role may require in the future.
This change also removes the linux build tag from ora.go. Oracle Instant Client libraries are now available for ARM-based Macs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/994)

oracle: Reconnect as a new role for each fixture

---

internal/sequencer/seqtest/seqtest.go
internal/sequencer/sequtil/lease_group.go
internal/source/objstore/conn.go
internal/staging/leases/leases.go
internal/staging/leases/leases_test.go
internal/staging/leases/provider.go
internal/types/types.go

This change updates the leases API to support the atomic acquisition of multiple names. Multiple names are acquired and renewed in an all-or-nothing behavior. This will allow finer-grained table leasing in sequencers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/992)

leases: Allow multiple names to be part of a lease

---

internal/target/schemawatch/backup_test.go
internal/target/schemawatch/coldata.go
internal/target/schemawatch/coldata_test.go
internal/target/schemawatch/dependencies.go
internal/target/schemawatch/dependencies_test.go
internal/target/schemawatch/watcher.go
internal/types/acceptors.go
internal/types/acceptors_test.go
internal/types/schema_data.go
internal/types/schema_data_test.go
internal/types/types.go

Previously, the table-dependency queries asked the target database to return the referential level of tables in the target schema. This change updates the queries to return parent-child tuples and computes the table-level within Replicator. Having the extra data within Replicator also allows us to compute the strongly-connected FK components within the target schema. This will enable an upcoming change to BestEffort mode to allow it to operate over groups of connected tables, rather than on a per-table basis.
Summary of changes:
- The SchemaData and ColData types are moved into a new file, schema_data_test.go.
- A SchemaData now expresses a variety of relationships between connected tables. This necessitates an update to how a SchemaData is serialized, and has a few knock-on effects in …

schemawatch: Extract table dependency information from target

---

internal/sequencer/besteffort/direct.go
internal/target/apply/apply.go
internal/target/apply/apply_test.go
internal/util/msort/msort.go
internal/util/msort/msort_test.go

Some logical frontends may only be able to provide sparse row data and may also provide multiple updates to the same key within a single target transaction. This change adds a per-key folding behavior to coalesce multiple sparse mutations, rather than pushing the complexity to the frontend.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/1007)

apply: Fold sparse mutations

---

internal/sequencer/script/script.go
internal/sequencer/script/source_acceptor.go

This change makes sourceAcceptor implement the MultiAcceptor interface directly. This will send fewer, larger batches downstream.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/1013)

sequencer/script: Make sourceAcceptor implement MultiAcceptor

---

internal/cmd/workload/runner.go
internal/sequencer/sequencer.go
internal/sequencer/sequencer_test.go
internal/source/kafka/integration_test.go
internal/source/mylogical/conn.go
internal/source/mylogical/conn_test.go
internal/source/mylogical/provider.go
internal/source/objstore/integration_test.go
internal/source/pglogical/conn.go
internal/source/pglogical/provider.go
internal/util/hlc/clock.go
internal/util/hlc/clock_test.go
internal/util/hlc/hlc.go
internal/util/hlc/hlc_test.go

As the number of logical frontends increases, the variety of external clock representations will continue to grow. This change introduces a monotonic Clock type and a way to associate an arbitrary external value with a Time.
Several frontends are updated to use a Clock instead of trying to adapt their upstream progress data into the Time type. The pglogical and mylogical frontends are prepared for an upcoming change to make them use an in-memory buffer around the core sequencer. Rather than generating MultiBatches, it is expected that frontends need only to assemble whole transactions in a TemporalBatch before handing the transaction off for processing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

hlc: Introduce a monotonic Clock type

---

internal/conveyor/metrics.go

The previous description implied that this metric tracks the age of the mutations, when, in fact, it tracks the age of checkpoints (resolved timestamps).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/1025)

conveyor: Revise source_lag_seconds description

---

.github/workflows/go-docker.yaml

The old-image cleanup can encounter a race condition between finding stale images and deleting them if multiple builds run concurrently. This is not a criticial build step, so we'll allow it to fail.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/1024)

workflows: Mark docker prune step as optional

---

internal/conveyor/config.go
internal/conveyor/conveyor.go
internal/sinktest/base/provider.go
internal/staging/checkpoint/checkpoint.go
internal/staging/checkpoint/checkpoint_test.go
internal/staging/checkpoint/group.go
internal/staging/checkpoint/options.go
internal/staging/checkpoint/stream.go

This change creates a core changefeed over the checkpoints table to allow multiple Replicator instances to notify one another to refresh their view of the table.
H/T: @BramGruneir for the reminder of
https://github.com/bobvawter/cacheroach/blob/512fae9092fc1e48406ef38fbb9959fc749d607f/pkg/store/cdc/cdc.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/1020)

checkpoint: Use core changefeed for fast notifications

---

internal/conveyor/config.go
internal/conveyor/conveyor.go
internal/sinktest/base/provider.go
internal/staging/checkpoint/checkpoint.go
internal/staging/checkpoint/checkpoint_test.go
internal/staging/checkpoint/group.go
internal/staging/checkpoint/options.go
internal/staging/checkpoint/stream.go

This change creates a core changefeed over the checkpoints table to allow multiple Replicator instances to notify one another to refresh their view of the table.
This behavior can be disabled with the `--disableCheckpointStream` flag.
The test framework ensures that the staging cluster has rangefeeds enabled to support the split-mode test cases (i.e. where the staging cluster is distinct from the source cluster).
H/T: @BramGruneir for the reminder of
https://github.com/bobvawter/cacheroach/blob/512fae9092fc1e48406ef38fbb9959fc749d607f/pkg/store/cdc/cdc.go
(cherry picked from commit 8d1519f25d5b14bbcdba065db5ab3b63568d8446)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/repl …

backport-v1.0: checkpoint: Use core changefeed for fast notifications

---

internal/sequencer/besteffort/besteffort_test.go
internal/sequencer/core/acceptor.go
internal/sequencer/core/core.go
internal/sequencer/core/metrics.go
internal/sequencer/core/provider.go
internal/sequencer/core/round.go
internal/sequencer/seqtest/check.go
internal/sequencer/seqtest/seqtest.go
internal/sequencer/seqtest/wire_gen.go
internal/sequencer/sequencer.go
internal/sequencer/sequtil/copier.go
internal/sequencer/sequtil/copier_test.go
internal/sequencer/staging/acceptor.go
internal/sequencer/staging/provider.go
internal/sequencer/staging/staging.go
internal/sequencer/staging/staging_test.go
internal/sequencer/switcher/group.go
internal/sequencer/switcher/provider.go
internal/sequencer/switcher/switcher.go
internal/sinktest/all/fixture.go
internal/sinktest/all/workload.go
internal/source/cdc/server/wire_gen.go
internal/source/cdc/wire_gen.go
internal/source/kafka/wire_gen.go
internal/source/objstore/wire_gen.go
internal/staging/stage/factory.go
internal/staging/stage/table_merger.go
internal/staging/stage/table_merger_test.go
internal/types/batch_reader.go
internal/types/types.go

This change allows the source of staging data provided to the Core sequencer to
be configured. The StagingCursor type is renamed to BatchCursor and a new
BatchReader interface defines a way to receive an asynchronous stream of cursors.
All existing code is updated to inject a Staging sequencer into the stack. This
sequencer provides an acceptor which writes incoming data to the staging tables
and injects the existing staging-reader implementation into Core.
The Core sequencer's acceptor is now a no-op. The workload checker is updated
to support providing data via BatchReader. This allows Core to be tested
without use of any staging tables.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

sequencer: Extract staging behavior from core

---

internal/source/cdc/handler.go

This change improves error reporting if a panic occurs during an HTTP request. A recovering deferred function is invoked by the runtime at the site of the panic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/1034)

cdc: Capture the stack of panics in the HTTP handler

---

internal/script/script_test.go
internal/sequencer/script/script_test.go
internal/sinktest/base/table_info.go
internal/source/mylogical/integration_test.go
internal/source/pglogical/integration_test.go
internal/target/apply/apply_test.go

Previously, product specific switch cases were used to determine how to build a query for the target database in the script test. We want to commonize this to a helper that can take care of the product specific logic and execute the query to find the row counts based on predicate.
Integrated this into the script test after implementing.
Resolves: #689
Release Note: None
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/1032)

sequencer: updated the script test so that it uses the new GetRowWithPredicate method

---

internal/staging/stage/stage.go
internal/staging/stage/stage_test.go

Integrate the batches.Window functionality from `util.Batches` to split up the work for MarkApplied in order to address concerns with sending payloads that exceed the sql.conn.max_read_buffer_message_size.
The new logic handles the processing of the mutations inside of batches.Window and sets the default window size to 100,000.
Resolves: #995
Release Note: None
**Testing**
- Hardcoded in a batch size of 1
- Inserted in 4 rows
- Verified that they get applied in individual batches
```
DEBUG  [Oct  1 17:45:13] MarkApplied: "_replicator"."public"."molt_public_tbl1"@{NO_FULL_SCAN} marked 1 mutations 
DEBUG  [Oct  1 17:45:15]                                               httpRequest="&{0x14000611c20 45 200 3 4.961584ms   false false}"
DEBUG  [Oct  1 17:45:15] upserted rows …
```

stage: updated the MarkApplied so that table updates happen in batches

---

internal/source/cdc/handler_test.go
internal/source/cdc/webhook.go

Resolves: #720
Release Note: None
**Testing**
```
go test -v -run ^TestIntegration$ github.com/cockroachdb/replicator/internal/source/cdc/server | tee test.log
...
{
"error": "table name is empty, please ensure the table name is included in the path",
"severity": "ERROR",
"timestamp": {
"seconds": 1728000632,
"nanos": 377887000
},
"uri": "/tgt-74858-58/public"
}
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/1035)

ident: made the empty table logging more clear when the CDC query webhook URI doesn't contain the table

---

internal/sequencer/sequtil/lease_group.go
internal/sequencer/sequtil/lease_group_test.go
internal/sinktest/all/fixture.go
internal/sinktest/all/wire_gen.go
internal/staging/leases/leases.go
internal/staging/leases/leases_test.go
internal/types/types.go

This change removes a copy-pasto that will cause LeaseGroup to exit if the underlying lease expires. The bulk of this change is allowing a test to access the Lease instance by way of Context.Value().
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/1054)

sequtil: Remove extraneous return statement from LeaseGroup

---

internal/conveyor/config.go
internal/conveyor/conveyor.go
internal/staging/checkpoint/checkpoint.go
internal/staging/checkpoint/checkpoint_test.go
internal/staging/checkpoint/group.go
internal/staging/checkpoint/migrate_test.go
internal/staging/checkpoint/options.go

Previously, customers manually had to skip backwards data checks by updating source code. This change makes it so that they can now pass in a flag to control the behavior of if they want to perform that check or not.
Resolves: #1046
Release Note: new flag that controls if the backwards data check can be skipped
**TODO**
**Local Testing**
When the `--ignoreBackwardsCheck` is specified (added debug logging for this then reverted). We verified above we can still invoke it to set it.
```
time="Oct 23 15:48:17" level=debug httpRequest="&{0x140004bea00 45 200 3 3.617709ms   false false}"
ignore check:  true
```
**Flag is hidden from help output**
```
--httpResponseTimeout duration   the maximum amount of time to allow an HTTP handler to execute for (default 2m0s)
--immediate …
```

conveyor/config: added new configuration for skipping backwards data checks
