cockroachdb/replicator

main_test.go, sink.go, sql.go
This change avoids inserting data into columns in the target table which are
hidden and which have a generation expression.  This improves compatibility
with schemas that use the hash-sharded index feature.
Fixes #47
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/48)
=> cdc-sink: Ignore hidden, generated columns

sink.go, sink_table.go, sink_table_test.go
This change defers reifying the contents of a Line until the actual upsert into
a table. The goal is to improve efficiency and to make it simpler to generate
batches of lines from sources other than a CockroachDB CDC feed.
Related: #64
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/67)
=> cdc-sink: Persist raw json

internal/source/cdc/handler.go, internal/source/cdc/handler_test.go, internal/source/cdc/ndjson.go, internal/source/cdc/resolved.go, internal/source/cdc/url_test.go, internal/source/cdc/webhook.go
This change simplifies parameter passing from the Handler.ServeHTTP method into
the leaf handler methods. This is in preparation for adding additional, common
URL paramaters in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/85)
=> cdc: Introduce a request type

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/92)
=> Update readme with demo feedback.

.github/docker-compose.yml, .github/workflows/tests.yaml
This change adds two additional PostgreSQL versions to the test matrix, per
customer request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/93)
=> workflow: Add pg11 and pg12 to test matrix.

README.md
These changes were based on the markdownlint extension in vscode, which in tern came from markdownlint library for node.js.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/105)
=> Minor style fixes to the README.md

.github/docker-compose.yml, .github/workflows/tests.yaml, internal/target/schemawatch/coldata.go, internal/target/sinktest/sinktest.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/142)
=> Add CockroachDB v22.1 to test matrix.

internal/target/sinktest/db_info.go
Tests in different packages are run in parallel by default. This can cause some
occasional conflicts between tests in different packages which pick the same
temporary database name. This change generates the temporary id by using the
process id and an internal counter, under the assumption that PIDs won't repeat
within a single execution of go test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/149)
=> sinktest: Improve uniqueness of temporary databases

internal/target/resolve/factory.go, internal/target/resolve/metrics.go, internal/target/resolve/resolve.go, internal/target/resolve/resolve_test.go, internal/types/types.go
Note to reviewers, this PR includes #151.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/152)
=> Add resolve package

internal/source/cdc/handler.go, internal/source/cdc/handler_test.go, internal/source/cdc/resolved.go, internal/source/cdc/webhook.go, internal/source/server/server.go, internal/target/resolve/resolve.go, internal/target/resolve/resolve_test.go, internal/types/types.go
Note to reviewers, this PR includes #151 and #152.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/153)
=> Make CDC endpoints use async resolver

.github/workflows/tests.yaml, go.mod, go.sum, tools.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/174)
=> workflow: Prettify test reports

.github/dependabot.yml
This change will make Dependabot pay attention to our workflow files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/176)
=> dependabot: Enable github-actions ecosystem

README.md
Also fix a few spelling errors as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/184)
=> Fix Readme to be markdownlint compliant

.github/workflows/docker.yaml, .github/workflows/golang.yaml
This aggregates the changes suggested by dependabot into a single PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/185)
=> actions: Version upgrade roll-up

.github/workflows/markdown.yaml, .markdownlint.yaml, README.md, scripts/README.md, scripts/demo_down.sh, scripts/demo_up.sh
The defaults are quite sane, so I say we stick to them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/186)
=> Add a Markdown Lint action

internal/source/pglogical/conn.go
The field reports a panic in this code, which could happen if no consistent
point has ever been reached when it's time to send a status update back to the
server. This case is now detected and logged for futher investigation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/192)
=> pglogical: Avoid panic on nil consistent point

.github/docker-compose.yml, .github/workflows/golang.yaml, internal/target/schemawatch/coldata.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/211)
=> workflow: Add CockroachDB v22.2 to matrix

internal/target/schemawatch/coldata.go
This change tweaks the parsing of user-defined types to handle a change in later 22.2.X releases where UDTs with mixed-cased names are returned as quoted strings by CockroachDB. The getColumns() function defers to ident.ParseIdent() to handle both quoted and unquoted type names, with and without dot separators.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/287)
=> schemawatch: Fix parsing of UDTs

internal/source/logical/metrics_events.go
Add a new metric that shows how far behind the destination cluster is from the current time.
Closes #286
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/288)
=> Add a new commit latency metric

internal/source/cdc/resolved_stamp.go, internal/source/cdc/resolver.go, internal/source/logical/chaos.go, internal/source/logical/dialect.go, internal/source/logical/factory.go, internal/source/logical/fan_events.go, internal/source/logical/logical_test.go, internal/source/logical/loop.go, internal/source/logical/serial_events.go, internal/source/pglogical/conn.go, internal/util/txguard/guard_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/299)
=> Loop leasing

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/302)
=> README: Update immedate-mode toggle

.github/docker-compose.yml, .github/workflows/golang.yaml
This change adds the latest release to the test matrix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/326)
=> workflow: Add PostgreSQL v15 to test matrix

internal/source/logical/config.go, internal/source/logical/logical_test.go, internal/source/pglogical/integration_test.go
10 mins seemed like a sane default.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/397)
=> turn on backfill mode by default and set it to 10 mins

internal/source/cdc/config.go, internal/source/cdc/resolver.go
This change improves the readability of resolver.readInto(). It also clarifies why there's a backup polling interval and makes it configurable. The comment on ReadInto() is out of date and has been removed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/490)
=> cdc: Clean up resolver.readInto

internal/target/schemawatch/dependencies.go, internal/target/schemawatch/dependencies_test.go
In the depOrderTemplatePg the where clause within the refs subquery has a redundant check for table_catalog, 
which should be a check for table_schema matching.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/502)
=> schemawatch: fix dependency query for constraints using different schema

internal/target/apply/apply_test.go
The TestAllDataTypes was incorrectly comparing the values stored in the target database with the values read from the same database.
The change verifies the values stored in the target database with the values stored in the staging database.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/533)
=> apply: Comparing the target and staging values in TestAllDataTypes

internal/source/mylogical/conn.go
This change allows a list of expected values for system variables.
Fixes: #562
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/563)
=> mysql: accept numeric values for enforce_gtid_consistency.

internal/util/msort/msort.go, internal/util/msort/msort_test.go
This change supports an upcoming PR that needs to consolidate mutations by (key, time) and not just by key. The repetitive code is extracted to a common, unexported function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/568)
=> msort: Add UniqueByTimeKey function

internal/target/apply/apply.go, internal/target/apply/apply_test.go, internal/util/retry/retry.go
This PR contains two commits to improve reliability when using Oracle Database as a target.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/650)
=> apply: Various Oracle Database improvements

internal/sinktest/all/fixture.go, internal/sinktest/all/wire_gen.go, internal/staging/checkpoint/checkpoint.go, internal/staging/checkpoint/checkpoint_test.go, internal/staging/checkpoint/group.go, internal/staging/checkpoint/metrics.go, internal/staging/checkpoint/provider.go, internal/staging/provider.go, internal/types/table_group.go
This PR is stacked on #674, #675, and #677. The relevant changes are in the tail commit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/679)
=> staging/checkpoint: Add checkpoint timestamp manager

internal/util/stopvar/stopvar_test.go
The test for DoWhenChangedOrInterval has a timing bug that was only visible on heavily-loaded test runners where the timer fired before the call to Set(). This change explicitly tests this flow by using a short timeout and a channel to control when the call to Set() is made.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/683)
=> stopvar: Fix timing bug in test

internal/target/apply/apply.go, internal/target/apply/apply_test.go
This change corrects a missed use case where reified values used in the delete key were not passed to the column's parse helper. The data-types test is updated to also attempt to delete the inserted row if the type is usable in the primary key.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/686)
=> apply: Transform key values in delete operations

internal/sequencer/besteffort/acceptor.go, internal/sequencer/besteffort/best_effort.go, internal/sequencer/besteffort/besteffort_test.go, internal/sequencer/switcher/switcher_test.go
This change fixes a bug in the BestEffort.Sweep implementation where the resolved timestamp window could incorrectly advance under certain timing conditions, even though there were still unapplied mutations. This would leave dangling mutations in the staging table. The problem is a logic bug in how Unstage is being used.
As previously written, the sweepOnce method would retry all staged mutations within the open resolved-timestamp window. If mutations had to be deferred a second time, they would have been marked with a deferral lease via the call to Unstage. In any a subsequent call to sweepOnce, there is no signal from Unstage that a mutation had been suppressed due to an existing lease, which should prevent the minimum bound of the window from advancing.
This change keeps the existng …
=> besteffort: Revise logic

internal/sequencer/besteffort/best_effort.go, internal/sequencer/besteffort/besteffort_test.go, internal/sequencer/sequencer.go, internal/sequencer/sequencer_test.go, internal/sinktest/all/fixture.go, internal/source/cdc/handler_test.go, internal/staging/stage/factory.go, internal/staging/stage/queries/unstage.tmpl, internal/staging/stage/stage_test.go, internal/staging/stage/templates_test.go, internal/staging/stage/testdata/ignore_lease.sql, internal/staging/stage/testdata/lease.sql, internal/staging/stage/testdata/unstage.sql, internal/staging/stage/testdata/unstage_limit.sql, internal/types/types.go
This PR contains a sequence of commits that correct bugs discovered while scale testing. In general, these would lead to BestEffort either hanging or leaving mutations stuck in the staging tables.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/707)
=> Additional bugfixes and performance improvements for BestEffort mode

.github/ISSUE_TEMPLATE/bug_report.md
Created with GitHub UI wizard
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/736)
=> Add a bug-report template

internal/types/batches.go
We use the noCopy linter trick to ensure that batch types are never copied. The current embedding makes the no-op `Lock()` method visible to potential callers, which is confusing and incorrect. This change makes the noCopy field anonymous, so these methods no longer pollute the exported API.
The TableBatch types was missing a noCopy marker, and this is now fixed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/742)
=> types: Fix noCopy API leakage

internal/staging/checkpoint/group.go
This change simplifies the query used to determine the active resolved-timestamp window. The previous structure of the query was due to confusion about timestamp ranges that had been cleaned up in #725.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/749)
=> checkpoint: Simplify resolved-timestamp bounds query

internal/staging/checkpoint/group.go
This change prevents the minimum bound of the resolving range from decreasing below the previous minimum value. If the checkpoint rewinds to the zero-time, it doesn't affect correctness since we track application on a per-mutation basis, but it does significantly increase the cost of finding new work to perform.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/759)
=> checkpoint: Use previous scan bounds as guaranteed minimum

.github/ISSUE_TEMPLATE/feature_request.md
Created with GitHub template generator
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/762)
=> Add Feature Request Issue Template

internal/util/stmtcache/stmtcache.go
This change is motivated by looking at mutex counts while under load. The metrics show about a 10:1 ratio of hits to misses in the default configuration. It's reasonable to trade repeated preparation of SQL and the prepared statements for unblocking most callers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/771)
=> stmtcache: Move preparation out of critical section

scripts/active_active/README.md
This change fixes the description of the merge. It also provide instructions to implement a "last write win" behavior.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/787)
=> active/active demo: clarifying merge behavior.

internal/staging/stage/stage.go
This supresses the `42P01 undefined_table` error code message if a staging table is created on demand after startup.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/792)
=> stage: Reduce log spam from metrics query

.github/workflows/go-tests.yaml, Dockerfile, go.mod
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/755)
=> build: Bump to go 1.22

internal/target/apply/apply_test.go
This test code created unused database transactions, since the apply helper facade doesn't actually accept a transaction.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cdc-sink/839)
=> apply: Remove no-op transaction in test

internal/sequencer/seqtest/check.go, internal/sinktest/sinktest.go, internal/source/cdc/config.go, internal/source/cdc/server/integration_test.go, internal/staging/stage/stage.go, internal/target/apply/apply_test.go, internal/target/dlq/dlq_schema.go, internal/types/types.go, internal/util/diag/diag.go, internal/util/metrics/metrics.go, internal/util/stdlogical/stdlogical.go, internal/util/stdpool/ora.go, internal/util/stdpool/pgx.go, internal/util/stdserver/config.go
Just some more renaming cleanup.  
Only one that might affect people is renaming the default application name for pgx.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/854)
=> A collection of more renames

scripts/shell_demo/demo_down.sh, scripts/shell_demo/demo_up.sh
This whole script probably needs to be updated.  I haven't tested it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/856)
=> Update scripts/shell_demo to replicator

internal/util/auth/jwt/claims.go, internal/util/auth/jwt/claims_test.go, internal/util/auth/jwt/jwt.go, internal/util/auth/jwt/sign.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/859)
=> Rename cdc-sink to replicator in util/auth/jwt

scripts/dashboard/README.md, scripts/dashboard/prometheus/prometheus.yml, scripts/dashboard/replicator.json
Also renames the cdc-sink.json file to replicator.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/870)
=> Rename cdc-sink to Replicator in the dashboard

Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/869)
=> Dockerfile: Rename cdc-sink to replicator

.github/docker-compose.yml, .github/workflows/go-build-cache.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/873)
=> Rename cdc-sink to replicator in two yaml file comments

internal/staging/stage/stage.go
This change adds an applied_at column for staging tables to allow customers to monitor mutation lag from within the database. No backfill behavior for existing tables is implemented, since staged rows are retired after 24h.  It would be possible to convert the applied column to a virtual one or retire it completely after sites have upgraded to this change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/889)
=> stage: Add applied_at column for staged mutations

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/897)
=> README: Remove outdated language

internal/sequencer/core/round.go
This changes the tryCommit method to send data to the target and staging databases concurrently. The staging transaction doesn't commit until the target transaction is known to be successful.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/907)
=> core: Apply and Mark concurrently

internal/conveyor/config.go, internal/source/kafka/config.go, internal/source/kafka/config_test.go, internal/source/kafka/consumer.go, internal/source/kafka/integration_test.go, internal/source/kafka/provider.go
This change properly adds the Conveyor and TLS configuration in the kafka connector.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/923)
=> kafka: properly wiring Conveyor,TLS config

.github/docker-compose.yml, .github/workflows/go-tests.yaml, internal/sinktest/all/integration.go, internal/source/objstore/conn_test.go, internal/source/objstore/integration_test.go
This change adds a simple smoke test that verifies we can read changefeed from a minio object store and replicated them to a target CockroachDB database.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/936)
=> objstore: adding smoke integration test

.github/docker-compose.yml, .github/workflows/go-tests.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/950)
=> workflows: Add CockroachDB v24.1 to the test matrix

internal/staging/stage/table_reader.go
If the retry loop in nextCursor retries, the reader's accumulator won't be cleared between retries. There's no overwhelming reason to want to save the accumulator instance between cycles, since we wind up moving the mutations into a MultiBatch. This change scopes the accumulator lifecycle to a single call to nextCursor() and queryOnce().
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/958)
=> stage: Use transient accumulator in tableReader

.github/workflows/go-tests.yaml, internal/sequencer/seqtest/check.go, internal/sinktest/base/log_config.go, internal/source/cdc/handler_test.go, internal/staging/stage/consistency.go, internal/staging/stage/consistency_test.go, internal/staging/stage/metrics.go, internal/staging/stage/stage.go, internal/staging/stage/table_merger_test.go, internal/staging/stage/table_reader.go, internal/staging/stage/table_reader_test.go, internal/types/types.go, internal/util/logfmt/logfmt.go, internal/util/logfmt/metrics.go, main.go, scripts/dashboard/README.md, scripts/dashboard/replicator.json, scripts/docker_c2c/run_compose.sh
This PR cherry-picks several commits on top of the v1.0.0 tag.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/961)
=> Cherry picks

go.mod
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/963)
=> go.mod: Bump toolchain to 1.22.6

internal/source/pglogical/conn.go
This change will log pgwire error messages received over the logical-replication stream. We also call out a ReadyForQuery message, which would indicate that the connection is unexpectedly in SQL mode.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/964)
=> pglogical: Log error wire messages from upstream

internal/cmd/dumphelp/dumphelp.go
This will let the wiki maintenance bot push updates for nested commands like `replicator workload pc run` and friends.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/997)
=> dumphelp: Descend into subcommands

internal/script/script_test.go, internal/script/testdata/main.ts
This change adds a userscript demo which shows how individual mutations can be rerouted by a user-defined apply function to a DLQ table.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/1016)
=> script: Demonstrate custom DLQ behavior

.gitignore
As part of my learning of replicator, I wanted to step through all of the code an life of mutations, so I went ahead and created some starter VSCode debugger configurations that can better help folks who want to onboard with VSCode. I'll gitignore these and share these files via zip file in Google drive.
Also aded a testdata directory that is gitignored since I have local testdata I want to use for my local testing but I don't want to check these into the repo.
Release Note: None
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/replicator/1029)
=> .vscode: added in debugger and testdata setup for VSCode
